### ISSUE TITLE
How to pass custom speaker prompt?

### ISSUE THREAD

**Issue by rishikksh20** [suno-ai/bark#1]
Hi, 
As I see you have provided some speaker prompt for the model, I want to send my voice as prompt rather than given what should I do that to convert my voice to prompt.

**Comment by valboldakov** [comment]
Hi, @rishikksh20 

Looks like you can't, because of

> However, to mitigate misuse of this technology, we limit the audio history prompts to a limited set of Suno-provided, fully synthetic options to choose from.

**Comment by gkucsko** [comment]
Hey there, sorry yes, given the power for misuse of technologies like these we try hard to takes steps to mitigate those issues. There are other verification techniques if we host the models ourselves (see upcoming Studio etc), however those don't work for a public release where you lose more control over how people use the models and whether they adhere to guidelines.
We are however planning to improve the number of prompts that we allow, and are also happy to listen to the community what types of prompts would be most useful (and ethical). Hope that helps!
