### ISSUE TITLE
German is Swiss German

### ISSUE THREAD

**Issue by padmalcom** [suno-ai/bark#101]
Hi, first of all: awesome work! I tried to run some tests in German but the output is, in all of my test cases, Swiss German. So for bark version 2 I'd review the german training data - or introduce a language tag.

**Comment by gkucsko** [comment]
thanks yeah i'm austrian so i played with it a bit :) right now it will be random in accent if you do it many times. people have requested separating it out in the future with an extra control tag like you mentioned, so might be worth doing that agreed

**Comment by padmalcom** [comment]
Haha I see, using custom history_prompts solves this "issue" for me.
