### ISSUE TITLE
system requirements

### ISSUE THREAD

**Issue by trappedinspacetime** [suno-ai/bark#11]
Amazing work! Thank you for publishing your project.
I have `Lenovo IdeaPad 3 15ALC6`  Ryzen 5500u 8GB RAM with no external GPU. I tried to test the examples. Unfortunately, it's extremly slow. 
After hours of struggling, I managed to finish the following code:

          from bark import SAMPLE_RATE, generate_audio
          from IPython.display import Audio
          
          text_prompt = """
               Hello.
          """
          audio_array = generate_audio(text_prompt)
          Audio(audio_array, rate=SAMPLE_RATE)
          
but it gave me no audio file.

Another point is that I like voice quality of Turkish speech model. I know there are legal issues but I  need that  Turkish speech model.

I hope you publish your speech model and instructions of how to build them.
All the best.

**Comment by gkucsko** [comment]
Hey, yes unfortunately for now it’s extremely slow on gpu. I suggest you try out the huggingface version or use google colab which comes with a free gpu.
