### ISSUE TITLE
No GPU being used

### ISSUE THREAD

**Issue by mike2003** [suno-ai/bark#12]
I have this message.
**No GPU being used. Careful**

But my is **Geforce 1660 Super**
What's wrong?

Driver Version: 472.12
CUDA Version: 11.4
Win10x64

**Comment by gkucsko** [comment]
Hm, what do you get for: torch.cuda.is_available()?

**Comment by mike2003** [comment]
false

**Comment by gkucsko** [comment]
Hm then this is a PyTorch issue. Sorry, hard to debug remotely. Have you used torch on gpu successfully in the past?

**Comment by gkucsko** [comment]
ah, yeah then i would look at torch tutorials (https://pytorch.org/get-started/locally/) unfortunately cuda is still a bit finicky, especially on older cards.
in the meantime for bark you can just use the huggingface spaces demo which has a UI or a google colab notebook which has a built-in gpu. that should get you started faster

**Comment by Fictiverse** [comment]
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`

**Comment by hippopotamus1000** [comment]
> `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117` worked for me

Did not work for me. I have CUDA 11.8 installed. I don't know what is missing.

**Comment by jjonj** [comment]
So the problem you have to solve is when running this in python:
 import torch
torch.cuda.device_count()
it returns 0. There are lots of google results for debugging that issue, on it myself atm.

**Comment by najeebl** [comment]
> > So the problem you have to solve is when running this in python: import torch torch.cuda.device_count() it returns 0. There are lots of google results for debugging that issue, on it myself atm.
> > The pip3 install did not help for me either and I have stable diffusion running fine
> 
> Try to run `pip uninstall torch torchvision` and then `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 `
> 
> This worked for me. (ChatGPT recommended this)

Worked for me as well.

**Comment by VGoich** [comment]
Torch does recognize my GPU, but when running the command for bark it can't seem to find it, out of ideas here

**Comment by shlomitgueta** [comment]
> > So the problem you have to solve is when running this in python: import torch torch.cuda.device_count() it returns 0. There are lots of google results for debugging that issue, on it myself atm.
> > The pip3 install did not help for me either and I have stable diffusion running fine
> 
> Try to run `pip uninstall torch torchvision` and then `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 `
> 
> This worked for me. (ChatGPT recommended this)

thanks its works for me too

**Comment by jxyk2007** [comment]
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
