### ISSUE TITLE
How can I save it as a wav file

### ISSUE THREAD

**Issue by god-ts** [suno-ai/bark#13]
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)
Audio(audio_array, rate=SAMPLE_RATE)

**Comment by gkucsko** [comment]
here you go, i should add this to the readme:
```
# convert audio array to 16-bit int represenation
import numpy as np
int_audio_arr = (audio_arr * np.iinfo(np.int16).max).astype(np.int16)
# save as wav
from scipy.io import wavfile
wavfile.write("my_file.wav", SAMPLE_RATE, int_audio_arr)
# save as mp3
from pydub import AudioSegment
audio_segment = AudioSegment(
    int_audio_arr.tobytes(),
    frame_rate=SAMPLE_RATE,
    sample_width=int_audio_arr.dtype.itemsize,
    channels=1,
)
audio_segment.export("my_file.mp3", format="mp3");
```

**Comment by god-ts** [comment]
The voice sounds strange, a little slow, and it is different from the webm in the demo or notebook.

**Comment by gkucsko** [comment]
hmm, slow is weird... i assume `SAMPLE_RATE` is 24_000?

**Comment by god-ts** [comment]
but i want to use it for my project and its also weird,not like the *.webm

**Comment by JonathanFly** [comment]
You can snag bark_speak.py from https://github.com/JonathanFly/bark if you just want to use command line.

**Comment by mcamac** [comment]
Added these instructions to README. Feel free to reopen if still an issue.
