### ISSUE TITLE
No GPU being used. Careful, inference might be extremely slow!

### ISSUE THREAD

**Issue by FreeL00P** [suno-ai/bark#130]
I try to run this demo, but it shows that the GPU cannot be found
![image](https://user-images.githubusercontent.com/87381094/234188988-b77d3aa4-3d67-4c95-a306-d487f63dccaf.png)

**Comment by openelch** [comment]
me too

**Comment by xe-james** [comment]
try to run a demo, but too slow caused faile to get the audio response, several minutes can't be done. how long do you guys can get the audio generated normally?

**Comment by YueHua46** [comment]
Try to create a new bat file and write：
![image](https://user-images.githubusercontent.com/83119504/234218993-5a40ac89-b0e3-4e87-9155-9c48e08cc89a.png)

**Comment by YueHua46** [comment]
I solved the problem by this
#https://github.com/suno-ai/bark/issues/16#issuecomment-1517197259 # # #

**Comment by gkucsko** [comment]
closing for now, try to get torch working with cuda independent of bark. basically bark will pick up cpu if `torch.cuda.is_available()` gives you True

**Comment by ZhaoYuanDaShi** [comment]
me too
