### ISSUE TITLE
non-speech sounds - how are they integrated?

### ISSUE THREAD

**Issue by padmalcom** [suno-ai/bark#133]
Hi, not really an issue but sth that makes me curious. You say that you are findind more and more non-speech sounds. Don't you have a list, e.g. from your training data? How are they integrated into the model, respectively how is it trained on those sounds?

**Comment by gkucsko** [comment]
they are part of the prompt in the same way as any other text, therefore they have a continuous representation and the model can learn to generalize, so there isn't really a list. the ones we listed we know occur but some others work too it's really cool :)
