### ISSUE TITLE
Turkey is the name of the country, Turkish is the language.

### ISSUE THREAD

**Issue by atilkan** [suno-ai/bark#134]
https://suno-ai.notion.site/Bark-Examples-5edae8b02a604b54a42244ba45ebc2e2

I don't know where these documents are so just putting an issue. It should be Turkish, not Turkey in the list below. 

<img width="328" alt="Screen Shot 2023-04-25 at 13 50 10" src="https://user-images.githubusercontent.com/68614829/234254993-911c0be5-3431-4f3a-8d24-01c3dafe5370.png">

**Comment by gkucsko** [comment]
whopps thanks! (I'm from austria so i take that typo to heart haha)
