### ISSUE TITLE
Support midi / musicXML

### ISSUE THREAD

**Issue by Coernel82** [suno-ai/bark#136]
As the AI can already sing is there the option to define pitches and lengths by midi or musicXML?
This would be an outstanding help for practice files for choirs.
The existing solutions sound extremely artificial.

**Comment by gkucsko** [comment]
great to know thanks, we are seeing quite some interest for the music use case. we'll try to get a sense on which knobs (types of input) are most needed for that

**Comment by gkucsko** [comment]
closing for now

**Comment by zhouhao27** [comment]
> As the AI can already sing is there the option to define pitches and lengths by midi or musicXML? This would be an outstanding help for practice files for choirs. The existing solutions sound extremely artificial.

I believe they have this technology already. Just check how suno ai works. They definitely used this technology already.

**Comment by fcnjd** [comment]
Sorry for bringing this up again, but I'm wondering. This issue has been closed as completed. So is it now possible to let Bark sing Midi or XML? I came also here by searching a better way to acomplish this than the solutions that exist right now.
Maybe I'm just missing something, but couldn't find instructions on how to do that somewhere. Thanks in advance for any hint on that.
