### ISSUE TITLE
1050Ti 4gb CUDA out of memory

### ISSUE THREAD

**Issue by Steelman14aUA** [suno-ai/bark#142]
Using gpu give an error, is there way to use --lowvram command on this?

Error:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 4.00 GiB total capacity; 3.51 GiB already allocated; 0 bytes free; 3.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by gkucsko** [comment]
try running like this and see if it works?
```
preload_models(
    text_use_small=True,
    coarse_use_small=True,
    fine_use_small=True,
    codec_use_gpu=False,
)
```

**Comment by gkucsko** [comment]
closing for now, feel free to reopen if not fixed

**Comment by Diyago** [comment]
![image](https://user-images.githubusercontent.com/8073766/235423931-9c491be1-342a-46c7-8f48-b2de1ae8a082.png)


same problem on 8gb

**Comment by gkucsko** [comment]
hmm very strange. most people report it working with 8gb GPUs. another things you can try is:
```import os
os.environ["SUNO_OFFLOAD_CPU"] = "True"```
that offloads each model after each inference step

**Comment by lombarthus** [comment]
Where do I implement this code snippet?
