### ISSUE TITLE
Incomplete installation under WSL2 I think.

### ISSUE THREAD

**Issue by razvanab** [suno-ai/bark#144]
I have followed the installation steps, and this is what I got:

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from bark import SAMPLE_RATE, generate_audio, preload_models
      2 from IPython.display import Audio
      4 # download and load all models

ModuleNotFoundError: No module named 'bark'

I tried with pip install bark and I got this:

ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from bark import SAMPLE_RATE, generate_audio, preload_models
      2 from IPython.display import Audio
      4 # download and load all models

ImportError: cannot import name 'SAMPLE_RATE' from 'bark' (/home/user/.local/lib/python3.10/site-packages/bark/__init__.py)

**Comment by chnl** [comment]
Same

**Comment by gkucsko** [comment]
not sure, but it looks like the install just didn't work? are you in the same venv?

**Comment by RickCarlino** [comment]
This issue seems identical to the one noted in https://github.com/suno-ai/bark/issues/56#issuecomment-1522639401
 Cross linking the issues for anyone who finds this via search.

**Comment by 3dluvr** [comment]
I have it running in WSL2, though I did not install it but cloned the repo so I can pull updates from the upstream.

This is what I have installed in my bark VENV

```
certifi==2022.12.7
charset-normalizer==3.1.0
cmake==3.26.3
einops==0.6.1
encodec==0.1.1
filelock==3.12.0
fsspec==2023.4.0
funcy==2.0
huggingface-hub==0.14.0
idna==3.4
Jinja2==3.1.2
lit==16.0.2
MarkupSafe==2.1.2
mpmath==1.3.0
networkx==3.1
numpy==1.24.3
packaging==23.1
PyYAML==6.0
regex==2023.3.23
requests==2.28.2
scipy==1.10.1
sympy==1.11.1
tokenizers==0.13.3
torch==2.0.0+cu118
torchaudio==2.0.1+cu118
tqdm==4.65.0
transformers==4.28.1
triton==2.0.0
typing_extensions==4.5.0
urllib3==1.26.15
```

**Comment by DeveloperOl** [comment]
I had the same issue. Do not use `pip install bark`, but `pip install git+https://github.com/suno-ai/bark.git` as mentioned in the readme. Working fine afterwards.

**Comment by gkucsko** [comment]
ah nice job, that's what must be happening for some people. unfortunately 'bark' was taken on public pypi
