### ISSUE TITLE
why no any sound

### ISSUE THREAD

**Issue by srtj** [suno-ai/bark#149]
how can let it have sound??
"from bark import SAMPLE_RATE, generate_audio, preload_models
from IPython.display import Audio
import torchaudio
# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)
print(audio_array)
# play text in notebook
s = Audio(audio_array, rate=SAMPLE_RATE)
torchaudio.get_audio_backend()"

**Comment by jungrea** [comment]
。you shoule save it as voice.

from scipy.io.wavfile import write as write_wav
write_wav("/path/to/audio.wav", SAMPLE_RATE, audio_array)

**Comment by srtj** [comment]
thanks
