### ISSUE TITLE
No GPU being used. Careful, inference might be very slow!

### ISSUE THREAD

**Issue by WyntersN** [suno-ai/bark#153]
![image](https://user-images.githubusercontent.com/27792650/234473180-be3d649d-52d5-4737-815c-1fe17b4dccda.png)
No GPU being used. Careful, inference might be very slow!

**Comment by WyntersN** [comment]
Why audio generated from characters over 500，It's only about 10 second

**Comment by winnerahao** [comment]
> Why audio generated from characters over 500，It's only about 10 second

I also encountered the same problem, it should be a parameter setting problem

**Comment by giorgionetg** [comment]
from my laptop with win 11 and a gtx 3060ti with 4gb vram the GPU isn't recognize and the first example it takes more than 10 minutes to run... is there a way to config? I ran also other projects with python and conda and stable diffusion and I never had problem with GPU..

**Comment by giorgionetg** [comment]
solved reinstalling torch following: https://pytorch.org/get-started/locally/

**Comment by gkucsko** [comment]
great! closing for now. as always when gpu isn't being used check `torch.cuda.is_available()`. if torch knows about the gpu then bark should too.
