### ISSUE TITLE
The long sentence

### ISSUE THREAD

**Issue by chikiuso** [suno-ai/bark#156]
Good morning, I try to run a hundreds words paragraph and shows the following message, and it just have 13 seconds long audio, is there any way I could make it longer audio? thanks.

>> Token indices sequence length is longer than the specified maximum sequence length for this model (843 > 512). Running this sequence through the model will result in indexing errors
WARNING:bark.generation:warning, text too long, lopping of last 69.6%

**Comment by jungrea** [comment]
Take a look at this PR https://github.com/suno-ai/bark/pull/84 for some clues.

**Comment by huzidev** [comment]
Try this repo for long sentences
https://github.com/JonathanFly/bark

**Comment by gkucsko** [comment]
Closing for now to have discussion in one place
