### ISSUE TITLE
Non-free LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [suno-ai/bark#162]
[encodec is no longer NC and is now MIT.](https://github.com/facebookresearch/encodec/issues/49)

Non-commercial (NC) clauses are non-free as they are not free software according to the [FSF](https://www.gnu.org/philosophy/free-sw.html#selling), open source according to the [OSI](https://opensource.org/osd#free-redistribution), or free culture according to [Freedom Defined](https://freedomdefined.org/Definition).  I would recommend using CC-BY-SA-4.0, CC-BY-4.0, or CC-0-1.0 instead which are free culture Creative Commons licenses.

**Comment by gkucsko** [comment]
Thanks yup exciting. We are gonna update that info in the readme soon and are currently double checking internally what that means for our models. Much appreciated

**Comment by gkucsko** [comment]
my bad reopening. stay tuned for announcement

**Comment by gkucsko** [comment]
fixed
