### ISSUE TITLE
Running out of memory (2070, 8 GB)

### ISSUE THREAD

**Issue by kallewoof** [suno-ai/bark#163]
Updating the README to indicate the amount of VRAM necessary would be very helpful as it's not clear right now if I'm way below required amount or just snuggling it.

**Comment by limapedro** [comment]
it seems that it needs 12 GB, I have 6 GB, i'm looking to run on CPU as of it now.

**Comment by C0untFloyd** [comment]
The latest commits helped a lot with memory management a lot. I made my own [fork](https://github.com/C0untFloyd/bark-gui) (with Gradio GUI) and develop/run this on a GTX 2060 Super with only 8 Gb. Perhaps when switching to use small models it might even run with 6 Gb.

**Comment by C0untFloyd** [comment]
They are downloaded & used when setting the Environment-Variable SUNO_USE_SMALL_MODELS or just use my fork where it is a cmdline-argument 😉

**Comment by gkucsko** [comment]
Closing for now as this should be possible using environment variables and preload_models.

**Comment by kallewoof** [comment]
@gkucsko Ideally, this would serve as a nudge to provide RAM details in the README. Not going to argue though.

**Comment by gkucsko** [comment]
thanks yea we are due for some documentation updates very soon
