### ISSUE TITLE
How do you install this? 

### ISSUE THREAD

**Issue by enfrte** [suno-ai/bark#166]
Hi, I have python 3.10.10 running. 

I've downloaded and unzipped the zip. Then ran 

```
[noel@family-desktop bark-main]$ python ./setup.py 
/usr/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:114: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
validate_pyproject.api.load_builtin_plugin defines `tool.distutils` schema
validate_pyproject.api.load_builtin_plugin defines `tool.setuptools` schema
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

```

What commands should I supply, or am I doing it wrong? 

Thanks.

**Comment by ThisNotDog** [comment]
The readme gives a sample script.

**Comment by gkucsko** [comment]
yup, either install directly from git or clone repo and use `pip install .`

**Comment by enfrte** [comment]
> yup, either install directly from git or clone repo and use `pip install .`

Ok thanks. I'm used to seeing such instructions earlier on in the readme.

**Comment by gkucsko** [comment]
@klmitch Hi, sorry for the cold mention. We are having a bunch of people running into issues doing `pip install bark` and getting the wrong package. I saw your bark project isn't really active anymore. Any chance you'd be willing to part with the 'bark' name on pypi? please shoot us a quick email at bark@suno.ai Thanks in advance, much appreciated!

**Comment by gkucsko** [comment]
Very much appreciated! My pypi username is gkucsko associated with email gkucsko at gmail.com

**Comment by klmitch** [comment]
I just deleted the sole release associated with that project.  Pypi now complains about not finding that project if you click the project in the results list for "bark".  Best guess is that they'll regenerate the results list either in a few hours or sometime overnight, and then "bark" will be free for the taking.

**Comment by klmitch** [comment]
And then I discovered that the project itself could be deleted, which I have done.  "bark" is completely free for the taking.  Enjoy.

**Comment by mcamac** [comment]
Many thanks! We appreciate it. Put a staging build up of the package to claim it.

**Comment by gkucsko** [comment]
Thanks a bunch! If you have a ‘buy me a coffee’ link we’d be happy to contribute something to your next coding streak! - Best, Suno Team
