### ISSUE TITLE
Windows: No GPU being used. Careful, inference might be very slow! 

### ISSUE THREAD

**Issue by jnpatrick99** [suno-ai/bark#173]
I installed torch 2.0.0 and CUDA 11.7 from PyTorch website. For example automatic's webui works perfectly and detects GPU without any problem. But Bark displays a `Windows: No GPU being used. Careful, inference might be very slow!` message.

I'm on Windows 10.

Is there any way to fix it? 

Update: Fixed it by running `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 --force-reinstall` after main installation.

**Comment by gkucsko** [comment]
great!

**Comment by dejavu1987** [comment]
I am on M1 Mac MacOS 13
I installed the torch packages 
```
pip3 install torch torchvision torchaudio
```
The pytorch website says # MPS acceleration is available on MacOS 12.3+

It still shows NoGPU being used, message. Is there something I need to change on the script??

**Comment by gkucsko** [comment]
you have set the env var SUNO_ENABLE_MPS to True. Note though that mps support is still experimental
