### ISSUE TITLE
Is there a relevant paper on bark?

### ISSUE THREAD

**Issue by Alex-Songs** [suno-ai/bark#177]
Is there a relevant paper on bark?

**Comment by OmarHory** [comment]
Same question..

**Comment by Jask-AI** [comment]
Spear-TTS by Google seems similar to this approach.
AudioLM and VALLE are the inspiration.

**Comment by gkucsko** [comment]
yeah ^^. we might put something together in the future but for now the above papers should give you a pretty clear idea on the general approach of bark
