### ISSUE TITLE
`EnCodec` is now released for commercial use

### ISSUE THREAD

**Issue by MarvinJWendt** [suno-ai/bark#179]
Hi, just a quick heads-up, `EnCodec` is now released under MIT, which allows commercial use.

This is in the README of Bark:
![image](https://user-images.githubusercontent.com/31022056/234812548-6745ab0a-ab06-40f2-a65d-bb25c9afd26e.png)

Here is the commit, where `EnCodec` changed the license: https://github.com/facebookresearch/encodec/commit/349b72939f57cb3bc7b60906c0ee8228c849485d

( https://github.com/facebookresearch/encodec/blob/main/LICENSE )

**Comment by gkucsko** [comment]
yup thanks, a few people have posted. we will update that line in the readme soon and see what it means for our models.
