### ISSUE TITLE
[Laughs], [sigh], what else?

### ISSUE THREAD

**Issue by coleTJC** [suno-ai/bark#190]
what other mannerisms are supported? i know at least [laughs], and [sighs] works but what other words are supported in brackets invoke different sounds?

**Comment by xenova** [comment]
According to the description of [this HF space](https://huggingface.co/spaces/suno/bark), you can use:

![image](https://user-images.githubusercontent.com/26504141/234996433-592288fc-a7a9-4feb-988f-c8eaf4df4c68.png)

**Comment by coleTJC** [comment]
@xenova oh sick thank you. I also got ChatGPT to generate a large list of possible candidates to play around with (some are cursed):

[whispers], [giggles], [snickers], [coughs], [groans], [yells], [gasps], [whimpers], [sobs], [murmurs], [chuckles], [hums], [sneezes], [grunts], [shrieks], [hiccups], [stammers], [stutters], [grumbles], [snorts], [howls], [moans], [guffaws], [sighs deeply], [laughs nervously], [cries], [sniffs], [smacks lips], [claps], [sings], [yawns], [mumbles], [shushes], [exhales sharply], [snaps], [whistles], [crunches], [slurps], [smacks], [clicks], [clinks], [clatters], [sizzles], [rustles], [splashes], [claps], [taps], [thumps], [rumbles], [drums], [jingles], [jangles], [pops], [bangs], [hisses], [scratches], [squeaks], [screeches], [buzzes], [swooshes], [swoops], [clangs], [whirrs], [chirps], [beeps], [tick-tocks], [thuds], [swishes], [crackles], [fizzes], [humming].

**Comment by xenova** [comment]
Oh wow nice! I actually missed it, but looks like the information I posted above was in the README all along: https://github.com/suno-ai/bark#%EF%B8%8F-details 🤣

**Comment by djbritt** [comment]
[upbeat music] 

Works sometimes.

**Comment by coleTJC** [comment]
@djbritt i notice quite a lot of possible words and word combinations exists and are viable, but it really is hit or miss.

**Comment by HaiFengZeng** [comment]
It seems the prompt doesn't work for some time?

**Comment by gkucsko** [comment]
sometimes meta tags work better with normal text on the left and right.
`I enjoyed it. [upbeat music] Now, I think it's time for something else.`

**Comment by adanpar** [comment]
hahaha

**Comment by cliooox** [comment]
xixixi

**Comment by netronom** [comment]
what about angry sounding voices 
did anyone tried it?

**Comment by gkucsko** [comment]
gonna close this since it isn't really an issue, please move to discussions

**Comment by ksylvan** [comment]
https://github.com/suno-ai/bark/discussions/265
