### ISSUE TITLE
Completely wrong output audio

### ISSUE THREAD

**Issue by djbritt** [suno-ai/bark#194]
I am using colab on Google.

The input is 

text_prompt = """
WOMAN: say this! Flubbidyfloppityfloopalooza when i Snazzlefrazzlewhippitywhamper
MAN: What did you say?
"""
audio_array = generate_audio(text_prompt, history_prompt="en_speaker_2")
Audio(audio_array, rate=SAMPLE_RATE)

The output doesn't say ANYTHING in here. Something like, 'reduced the medical steps, this was felt with the female uh..."

Am I doing something wrong?

**Comment by djbritt** [comment]
I think speaker 2 has issues, the other speakers don't output the wrong audio as much.

**Comment by gkucsko** [comment]
loll yeah some prompts work better than others, we are looking into ways to better organize them
