### ISSUE TITLE
Bark not running the prompt code. Error: Encodec?

### ISSUE THREAD

**Issue by CaBaccoRic** [suno-ai/bark#200]
Hi there, my issue is the following:
when pointing CMD with admin privilege to a BarkAI folder in C:\\ it outputs the following issue:

_from encodec import EncodecModel
ModuleNotFoundError: No module named 'encodec'_

(on another machine it works fine but only with CPU. I wanted to try CUDA for faster generations)

Hope someone can give feedback!

**Comment by CaBaccoRic** [comment]
Tried this and worked:

pip install -U encodec  # stable release
pip install -U git+https://git@github.com/facebookresearch/encodec#egg=encodec  # bleeding edge
# of if you cloned the repo locally
pip install .

**Comment by mcamac** [comment]
Glad it worked! Will look at adding this into FAQ

**Comment by artificialnouveau** [comment]
Still facing the same issue, even with the:

pip install -U encodec # stable release
pip install -U git+https://git@github.com/facebookresearch/encodec#egg=encodec
pip install .

**Comment by artificialnouveau** [comment]
I had the same issue. So I ran:

pip install -U encodec # stable release
pip install -U git+https://git@github.com/facebookresearch/encodec#egg=encodec
pip install .

Now I get this error:

  File "./bark-with-voice-clone/bark/generation.py", line 8, in <module>
    from encodec import EncodecModel

ImportError: cannot import name 'EncodecModel' from 'encodec' (unknown location)
