### ISSUE TITLE
Can the license be updated now that Encodec is MIT licensed?

### ISSUE THREAD

**Issue by SamHjelmfelt** [suno-ai/bark#214]
This week, Encodec was updated to an MIT license:(https://github.com/facebookresearch/encodec/commit/349b72939f57cb3bc7b60906c0ee8228c849485d).

Can Bark be updated as well? The README makes it sound like the Encodec license was the only reason for Bark's non-commercial license.
"Bark is licensed under a non-commercial license: CC-BY 4.0 NC. The Suno models themselves may be used commercially. However, this version of Bark uses EnCodec as a neural codec backend, which is licensed under a [non-commercial license](https://github.com/facebookresearch/encodec/blob/main/LICENSE)."

**Comment by gkucsko** [comment]
thanks, closing as duplicate https://github.com/suno-ai/bark/issues/162
