### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/audio.wav'

### ISSUE THREAD

**Issue by ch4r1ty** [suno-ai/bark#218]
when running these codes below: 

from scipy.io.wavfile import write as write_wav
write_wav("/path/to/audio.wav", SAMPLE_RATE, audio_array)

terminal says:  FileNotFoundError: [Errno 2] No such file or directory: '/path/to/audio.wav'

**Comment by gkucsko** [comment]
you have to specify a path to  where you want to save you file and that directory has to exist. `/path/to/audio.wav` is just a placeholder

**Comment by huzidev** [comment]
> 

simple create these folder inside yours root directory with that specific name
path > to 
both path and to are the name of the folders in which yours audio file is going to be save

**Comment by gkucsko** [comment]
gonna close. feel free to reopen if still not working. Using the huggingface GUI might be another easy to use approach to get started with
