### ISSUE TITLE
How to select certain gpu?

### ISSUE THREAD

**Issue by Marcophono2** [suno-ai/bark#220]
Hello!
Respect, I am very impressed by this work and the voices' quality! For my purpose the inference is way to slow but I will surely follow this project. I have 3 GPUs in my computer and only cuda:0 is permanent in use by another project. Depending on the gpu load, sometimes I get a short time frame when around 8 GB of VRAM are available and bark runs. What you wrote, the inference is about realtime. (RTX 4090, Pytorch 2.0, cuda 12 (but the cuda compiler is 11.8...may be here is an issue but I don't think so))
Anyway, my question is: How can I tell bark to use cuda:2 for the model? I set some device="cuda:2" at different spots in generation.py and model.py but without any success. It always uses cuda:0.

And one question to the text input: Am I right that two lines are the maximum? Is this documented anywhere? I often miss some informations although I read the same piece of text 2 or 3 times so I will not surely exclude that I was blind again. :-)

Best regards
Marc

**Comment by mcamac** [comment]
We probably need to look into the `device` issue. Stand by for updates...

Re text input, check out this PR for open work onit: #84

**Comment by actionless** [comment]
just setting `CUDA_VISIBLE_DEVICES=1` etc env var works for me
