### ISSUE TITLE
why is voice cloning disabled?

### ISSUE THREAD

**Issue by yosun** [suno-ai/bark#223]
Can voice cloning simply be a disclaimer instead of technically disabled, as indicated in readme? 

`Bark has the capability to fully clone voices - including tone, pitch, emotion and prosody. The model also attempts to preserve music, ambient noise, etc. from input audio. However, to mitigate misuse of this technology, we limit the audio history prompts to a limited set of Suno-provided, fully synthetic options to choose from for each language.`

**Comment by gkucsko** [comment]
unfortunately that wouldn't really be a way to enforce anything in regards to misuse
