### ISSUE TITLE
Language support for Tamil - World's widely spoken classic language

### ISSUE THREAD

**Issue by vasanthkumar-in** [suno-ai/bark#23]
Kindly add the support for Tamil language as well.

There are so much of speech datasets available online from OpenSLR MILE, IIT Madras etc.

Thanks,
Vasanth

**Comment by gkucsko** [comment]
thanks ya all a question of data prep time etc, but we will definitely put on roadmap thanks!

**Comment by pj8912** [comment]
any update on this??
