### ISSUE TITLE
memory_profiling_bark.ipynb inconsistency

### ISSUE THREAD

**Issue by MAkcanca** [suno-ai/bark#234]
I was reading this [memory_profiling_bark.ipynb](https://github.com/suno-ai/bark/blob/main/notebooks/memory_profiling_bark.ipynb) notebook, and the method to test with/without CPU offloading seems a bit inconsistent to me, maybe I'm missing it.

`for offload_models in (True, False):`
We define offload_models in here, but don't use it anywhere in the code except prints. Shouldn't it be like

`os.environ["SUNO_OFFLOAD_CPU"] = offload_models`

@gkucsko

**Comment by gkucsko** [comment]
@mikeyshulman i believe fixed

**Comment by mikeyshulman** [comment]
just pushed a fix. Thanks for catching this bug!
