### ISSUE TITLE
torchaudio 报错

### ISSUE THREAD

**Issue by owlsaea** [suno-ai/bark#239]
FileNotFoundError: Could not find module 'G:\Python310\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by gkucsko** [comment]
`pip uninstall torch torchaudio torch vision` and `pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` or similar (whichever torch version you need) should do the trick

**Comment by gkucsko** [comment]
gonna close for inactivity. feel free to reopen if not fixed

**Comment by aniket-rudder** [comment]
I have tried reinstalling torch torchaudio torch vision still facing the error - **FileNotFoundError: Could not find module 'C:\Users\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.**

**Comment by ksclunie** [comment]
I have also been unable to overcome this error. I have tried installing different versions of torch audio and specifying the path in different ways.

**Comment by sneha117** [comment]
> pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

Tried it, still gets the error

FileNotFoundError: Could not find module 'C:\Users\XTEND\anaconda3\envs\nemo_torch_gpu\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
