### ISSUE TITLE
Swedish language support!

### ISSUE THREAD

**Issue by chille9** [suno-ai/bark#24]
Just wanted to give my two cents and kindly ask for Swedish language support. Much love.

**Comment by linhduongtuan** [comment]
@chille9 I also love this repo and want to train for Vietnamese. 
How can I contribute for this repo @mcamac, @gkucsko, @kmfreyberg and @mikeyshulman.
It could be better if the authors can release train.py and describe more detail how to reproducible/reimplement these experiments
Best regards,
Linh

**Comment by gkucsko** [comment]
thanks, we'll put swedish and vietnamese on the roadmap. For now our training code is too tied into our other projects but there are other great repos that can give you a good sense on what it would look like to write one: https://github.com/lucidrains/audiolm-pytorch
