### ISSUE TITLE
ModuleNotFoundError: No module named 'bark'

### ISSUE THREAD

**Issue by R-802** [suno-ai/bark#243]
Any fix for this? I'm getting this issue in all notebooks.
![image](https://user-images.githubusercontent.com/109842181/236105771-74c5f21b-633e-47be-80bf-73a8e5363d84.png)
![image](https://user-images.githubusercontent.com/109842181/236105894-96412763-59af-42ef-b539-884ea126437d.png)

**Comment by gkucsko** [comment]
looks like bark isn't found. did you install it correctly?

**Comment by R-802** [comment]
Nope, sorry about that.
