### ISSUE TITLE
Multi-lingual voice cloning

### ISSUE THREAD

**Issue by takan1** [suno-ai/bark#25]
Hi, Thanks for the great work :) 
I'm interested in multilingual voice cloning and seems like there is valle-x. 
https://vallex-demo.github.io/

Is this something Bark can handle (maybe in the future)?

**Comment by gkucsko** [comment]
yup should already work. we provide 10 prompts for each language that we support. you can specify them via `history_prompt="{lang_code}_speaker_{0-9}"`
as for cloning a custom voice we prevent that for now to make sure there is no misuse of the technology

**Comment by DedaDev** [comment]
> as for cloning a custom voice we prevent that for now to make sure there is no misuse of the technology

that is inevitable.

**Comment by bobwatcherx** [comment]
please tell me how to voice clone my voice.  i will use it for private and not public .  Can it
