### ISSUE TITLE
FileOutput is encoded in float

### ISSUE THREAD

**Issue by roxyrypler** [suno-ai/bark#252]
#### Information:
I am using this example.
I have changed out the Audio() output to a write_wav().
Am on windows and running it within a conda env. (am not using notebook)

It was working until i updated latest version of bark.

###Code i use:
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import nltk  # we'll use this to split into sentences
import numpy as np
from scipy.io.wavfile import write as write_wav
from bark.generation import (
    generate_text_semantic,
    preload_models,
)
from bark.api import semantic_to_waveform
from bark import generate_audio, SAMPLE_RATE

preload_models()

script = """
Hey, have you heard about this new text-to-audio model called "Bark"?
""".replace("\n", " ").strip()

sentences = nltk.sent_tokenize(script)

SPEAKER = "v2/en_speaker_6"
silence = np.zeros(int(0.25 * SAMPLE_RATE))  # quarter second of silence

pieces = []
for sentence in sentences:
    audio_array = generate_audio(sentence, history_prompt=SPEAKER)
    pieces += [audio_array, silence.copy()]

write_wav(f"speech.wav", SAMPLE_RATE, np.concatenate(pieces))
```

The output file size seems right, but when i try to open the file up in Windows media player it says its encoded with "Floats".

Is there a workaround for this? or any other methods of outputting the audio to disk?

**Comment by roxyrypler** [comment]
After some more testing it seems to be the silence thats causing the faulty audio output. not sure why

**Comment by JonathanFly** [comment]
It's a float32 wav. It's a valid format but kind of unusual, and twice as big as a typical wav. You can play it with VLC just fine for example.

Although I might be misunderstanding, because you should have had the same problem in the previous version too. Or maybe the Audio() widget converts it and you downloaded it from that? In any case easiest fix is to just use a library like soundfile and give it the same input.

```
import soundfile
soundfile.write(output_filepath, audio_arr, SAMPLE_RATE,format='WAV', subtype='PCM_16')
```

**Comment by roxyrypler** [comment]
Perfect, thanks! That worked.
