### ISSUE TITLE
Question about generate_text_semantic

### ISSUE THREAD

**Issue by asr-pub** [suno-ai/bark#256]
```
if merge_context:
    tok_emb = torch.cat([
        self.transformer.wte(idx[:,:256]) + self.transformer.wte(idx[:,256:256+256]),
        self.transformer.wte(idx[:,256+256:])
    ], dim=1)
```
In the generate_text_semantic process, Why we plus the token embedding and semantic_history embedding, I think we didn't need to plus semantic_history embedding ?

**Comment by gkucsko** [comment]
just to save a bit of space in the prompt. you are right, concatting would be the standard thing to do. would probably give a small performance increase, but i would guess nothing crazy. prob will go back to that when we go beyond 1024 block size

**Comment by asr-pub** [comment]
So, while in training process(text -> semantic), the data flow is (text embedding + prompt semantic embedding) -> semantic embedding ?

**Comment by asr-pub** [comment]
So, while in training process(text -> semantic), the data flow is (text embedding + prompt semantic embedding) -> semantic embedding ? should we concat the text of the prompt ?

**Comment by gkucsko** [comment]
yup! can't really change it without retraining. pretty sure it won't make a gigantic difference in performance but i put on our todo list for next version, especially once we go beyond 1024

**Comment by asr-pub** [comment]
Thank you for your replying, I have another question : 
1. the training process ( semantic -> coarse tokens )，the data flow is concat(semantic embedding, prompt coarse embedding) -> coarse tokens ? 
2. If so, it's difference with Google's Spear-TTS, the Spear-TTS is (<semantic of prompt>, <semantic>, <coarse of prompt> -> <coarse>) , do u compare the Google's, which is better ?

**Comment by asr-pub** [comment]
Thank you for your replying, I have another question :

1. the training process ( semantic -> coarse tokens )，the data flow is **concat**(semantic of prompt, semantic, prompt coarse) -> coarse tokens ?

**Comment by gkucsko** [comment]
gonna close since it's not a functional issue
