### ISSUE TITLE
NVIDIA GeForce GTX 1650

### ISSUE THREAD

**Issue by StepHaze** [suno-ai/bark#257]
Hello,
is my NVIDIA GeForce GTX 1650 (~4GB) good for speech generation?
Can I convert large text to speech at a time?

Thank you.

**Comment by gkucsko** [comment]
should be fine if you offload the models between steps and maybe use the small models, see here: https://github.com/suno-ai/bark/blob/main/notebooks/memory_profiling_bark.ipynb
