### ISSUE TITLE
How can I install bark in win10 correctly?

### ISSUE THREAD

**Issue by changlehu** [suno-ai/bark#26]
C:\Users\winner\Desktop>pip install git+https://github.com/suno-ai/bark.git
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting git+https://github.com/suno-ai/bark.git
  Cloning https://github.com/suno-ai/bark.git to c:\users\winner\appdata\local\temp\pip-req-build-uky214xt
  Running command git clone --filter=blob:none -q https://github.com/suno-ai/bark.git 'C:\Users\winner\AppData\Local\Temp\pip-req-build-uky214xt'
  Resolved https://github.com/suno-ai/bark.git to commit 2a602ce8762ed0346f3af90ab9297a41eee40ad3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=7318 sha256=b171442666007d18d81628603548eb93bc889aa3fbcfdc011c1b9c3e7feb3e83
  Stored in directory: C:\Users\winner\AppData\Local\Temp\pip-ephem-wheel-cache-fmy74ei2\wheels\5d\50\6d\04e99a146c274ebc61149dfd86e7f046aa2772170a0bc978d3
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0

**Comment by changlehu** [comment]
It is a wrong package name. How to make it right?

**Comment by changlehu** [comment]
Sorry. I know what is wrong now. python >3.8 My python is 3.6.

**Comment by changlehu** [comment]
I‘ve installed python 3.11.3. The package bark can be installed now. I copied sample code and tried to run it. But .... the sound file is so big. so I had to quit. Is there something wrong? 
----------
No GPU being used. Careful, Inference might be extremely slow!
  0%|▏                                            | 16.2M/5.35G [00:04<14:37, 6.08MiB/s]
  0%|▏                                            | 18.0M/5.35G [00:04<11:32, 7.70MiB/s]
  0%|▏                                            | 19.1M/5.35G [00:04<10:48, 8.23MiB/s]
  0%|▏                                            | 20.2M/5.35G [00:04<09:59, 8.89MiB/s]

**Comment by changlehu** [comment]
It's the code what i ran:
----------
from bark import SAMPLE_RATE, generate_audio
from IPython.display import Audio
from scipy.io.wavfile import write as write_wav

text_prompt = """
     Hello, my name is Suno. And, uh 鈥?and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)
Audio(audio_array, rate=SAMPLE_RATE)
write_wav("audio.wav", SAMPLE_RATE, audio_array)

**Comment by mcamac** [comment]
Hi, those progress bars are the models being downloaded (this happens once, and they are 5-10GB total).

So audio generation is not happening yet.

**Comment by changlehu** [comment]
Thanks. I mean. I will try on.

**Comment by asadal** [comment]
> C:\Users\winner\Desktop>pip install git+https://github.com/suno-ai/bark.git Looking in indexes: http://mirrors.aliyun.com/pypi/simple/ Collecting git+https://github.com/suno-ai/bark.git Cloning https://github.com/suno-ai/bark.git to c:\users\winner\appdata\local\temp\pip-req-build-uky214xt Running command git clone --filter=blob:none -q https://github.com/suno-ai/bark.git 'C:\Users\winner\AppData\Local\Temp\pip-req-build-uky214xt' Resolved https://github.com/suno-ai/bark.git to commit [2a602ce](https://github.com/suno-ai/bark/commit/2a602ce8762ed0346f3af90ab9297a41eee40ad3) Installing build dependencies ... done Getting requirements to build wheel ... done Installing backend dependencies ... done Preparing metadata (pyproject.toml) ... done Building wheels for collected packages: UNKNOWN Building wheel for UNKNOWN (pyproject.toml) ... done Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=7318 sha256=b171442666007d18d81628603548eb93bc889aa3fbcfdc011c1b9c3e7feb3e83 Stored in directory: C:\Users\winner\AppData\Local\Temp\pip-ephem-wheel-cache-fmy74ei2\wheels\5d\50\6d\04e99a146c274ebc61149dfd86e7f046aa2772170a0bc978d3 Successfully built UNKNOWN Installing collected packages: UNKNOWN Successfully installed UNKNOWN-0.0.0

I have the same issue. Ubuntu22.04 LTE, Python 3.10.6
How can I solve it?

**Comment by Mingxiangyu** [comment]
> Sorry. I know what is wrong now. python >3.8 My python is 3.6.

@asadal 你的错误可能也是这个！

**Comment by Anthonyg5005** [comment]
Using windows 11 but should be the same. I just installed jupyter lab and used the same first 3 scripts from the Google colab and it worked fine

**Comment by Anthonyg5005** [comment]
Using windows 11 but should be the same. I just installed jupyter lab and used the same first 3 scripts from the Google colab and it worked fine

**Comment by Anthonyg5005** [comment]
Using windows 11 but should be the same. I just installed jupyter lab and used the same first 3 scripts from the Google colab and it worked fine

**Comment by Anthonyg5005** [comment]
Using windows 11 but should be the same. I just installed jupyter lab and used the same first 3 scripts from the Google colab and it worked fine

**Comment by Anthonyg5005** [comment]
Using windows 11 but should be the same. I just installed jupyter lab and used the same first 3 scripts from the Google colab and it worked fine

**Comment by Anthonyg5005** [comment]
Using windows 11 but should be the same. I just installed jupyter lab and used the same first 3 scripts from the Google colab and it worked fine

**Comment by merecesarchviz** [comment]
for those like me who need help, here is from a person who really likes to help and explain! https://www.youtube.com/watch?v=w41-MUfxIWo

**Comment by gkucsko** [comment]
looks like this is fixed? closing for now, feel free to reopen if still issues

**Comment by asadal** [comment]
Thanks a lot! ;-)
