### ISSUE TITLE
Long sentences

### ISSUE THREAD

**Issue by tin2tin** [suno-ai/bark#260]
No matter what solution I try to implement either bad audio(too short sentences) or sentences not spoken to the end. So, as a challenge, can anyone here with the various sting splitting methods used get a full render of this text?

> It was a chilly November afternoon.  I had just consummated an unusually hearty dinner, of which the dyspeptic truffe formed not the least important item, and was sitting alone in the dining-room, with my feet upon the fender, and at my elbow a small table which I had rolled up to the fire, and upon which were some apologies for dessert, with some miscellaneous bottles of wine, spirit and liqueur. 

From: https://poestories.com/read/angeloftheodd

**Comment by C0untFloyd** [comment]
Used my [fork](https://github.com/C0untFloyd/bark-gui) quick generation, speaker v2/en_speaker_6 - random Seed 2257623070:

[final_17-19-41_s2257623070.webm](https://user-images.githubusercontent.com/131583554/236687287-80271c8a-06cb-414c-99a1-860053f85f24.webm)

![Screenshot](https://user-images.githubusercontent.com/131583554/236686908-c24d55ff-7ad6-4979-9514-012c20978f41.png)

Tried 3 times with different speakers, did fail more or less like you wrote with speakers 0 & 1 but first try with en_speaker_6 resulted in this audio-file. Above Screenshot is from my WIP version where you can input a seed for reproducing results, but splitting and generating should be the same with the already downloadable older release.

**Comment by gkucsko** [comment]
interesting.. have you played with `min_eos_p`?

**Comment by gkucsko** [comment]
basically the model has an EOS character that it can emit at any time (trained to come after it's finished). Now we could just treat it like any other codebook entry and if we happen to sample it we abort or we set a probability threshold like `min_eos_p`, where if the probability is above that threshold we abort.
so yeah, basically the inverse from what you would assume from the comment haha. lower `min_eos_p` means earlier termination on average

**Comment by C0untFloyd** [comment]
Thanks for the explanation and thank you for creating Bark in first place!

**Comment by gkucsko** [comment]
gonna close in favor of discussion
