### ISSUE TITLE
Regarding the problems I encountered in use, my own simple solution

### ISSUE THREAD

**Issue by wyl2000** [suno-ai/bark#261]
My installation method is to enter cmd from the windows address bar under D. I have installed stablediffusion in my win11 system, and my system environment should be fine.
The installation is normal, I enter python under cmd, enter python, but execute
from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio
preload_models()
Encountered the problem of downloading the model continuously, the downloaded model arrives (everyone's account computer is different)
C:\Users\Administrator\.cache\huggingface\hub
There are many files with more than 2G in it
MD5: B3E42BCBAB23B688355CD44128C4CDD3
Should be the same file with a different name
Python prompts me that I do not have permission to transfer this file to model\text.pt
I manually changed the name and moved it to the model. This problem still occurs. I restarted the computer. I don’t know what I did. Finally, I downloaded different files and finally skipped the problem of continuously downloading the model.
Until now, I don't know how to set it up, but it works anyway.
Finally I know where my sound templates are
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\bark\assets\prompts
See where python is installed, you can guess, this will be useful later
how do i use it
Enter python on the command line
After the version number appears, there is >>> input below
from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio
preload_models()
The following situation will appear, remember to press Enter after preload_models() appears
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from bark import SAMPLE_RATE, generate_audio, preload_models
>>> from scipy.io.wavfile import write as write_wav
>>> from IPython.display import Audio
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'IPython'
>>> preload_models()
>>>
enter
text_prompt = """
     I have a silky smooth voice, and today I will tell you about
     The exercise regimen of the common sloth.
"""
audio_array = generate_audio(text_prompt, history_prompt="v2/en_speaker_1")
write_wav("1.wav", SAMPLE_RATE, audio_array)
The audio will be generated to the Administrato account name is 1.wav
I don’t know much about python. I opened it and looked it up. I couldn’t figure it out, but there are many explanations for this thing. The time is only about 13 seconds. Generating Chinese is a foreigner accent

text_prompt = """
      Fuck, it’s okay like this, but it can’t be automatically deposited, and there are many problems.
"""
audio_array = generate_audio(text_prompt, history_prompt="v2/zh_speaker_1")
write_wav("1.wav", SAMPLE_RATE, audio_array)

There is a v2 folder under bark\assets\prompts with 9 Chinese templates, which can be zh_speaker_0 to zh_speaker_9
You can also use history_prompt="zh_speaker_1") directly, because there are also 9 files under the prompts, and the MD5 is different after comparison. I know too little, so I can't infer how to play this bark. It is estimated that the developers know best and are flexible. Those who don’t understand the code can only rely on my guess. How to set it and dare not mess with it can’t solve the problem. The setting can only be changed from the code, which is too difficult.
For the generation of long audio, I can only make a Long-Form Dialog with Bark, enter python
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

from IPython.display import Audio
import nltk # we'll use this to split into sentences
import numpy as np

from bark.generation import (
     generate_text_semantic,
     preload_models,
)
from bark.api import semantic_to_waveform
from bark import generate_audio, SAMPLE_RATE

preload_models()

speaker_lookup = {"Samantha": "v2/en_speaker_9", "John": "v2/en_speaker_2"}

# Script generated by chat GPT
script = """
Samantha: Hey, have you heard about this new text-to-audio model called "Bark"?

John: No, I haven't. What's so special about it?

Samantha: Well, apparently it's the most realistic and natural-sounding text-to-audio model out there right now. People are saying it sounds just like a real person speaking.

John: Wow, that sounds amazing. How does it work?

Samantha: I think it uses advanced machine learning algorithms to analyze and understand the nuances of human speech, and then replicates those nuances in its own speech output.

John: That's pretty impressive. Do you think it could be used for things like audiobooks or podcasts?

Samantha: Definitely! In fact, I heard that some publishers are already starting to use Bark to create audiobooks. And I bet it would be great for podcasts too.

John: I can imagine. It would be like having your own personal voiceover artist.

Samantha: Exactly! I think Bark is going to be a game-changer in the world of text-to-audio technology."""
script = script.strip().split("\n")
script = [s.strip() for s in script if s]
script

Display the dialog after the script has been changed, enter after pressing Enter
pieces = []
silence = np.zeros(int(0.5*SAMPLE_RATE))
for line in script:
     speaker, text = line. split(": ")
     audio_array = generate_audio(text, history_prompt=speaker_lookup[speaker], )
     pieces += [audio_array, silence.copy()]
To enter twice one of them appears...
but in the end

Audio(np. concatenate(pieces), rate=SAMPLE_RATE)

failure prompt
  Audio(np. concatenate(pieces), rate=SAMPLE_RATE)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
NameError: name 'Audio' is not defined
This is stupid, it can’t be synthesized, but this one can still be generated, and the other two examples hang up at the beginning
try
write_wav("1.wav", SAMPLE_RATE, audio_array)
Still can only generate the last file for more than 10 seconds.

**Comment by gkucsko** [comment]
gonna close since this isn't really an issue
