### ISSUE TITLE
Mandarin not accurate

### ISSUE THREAD

**Issue by komagic** [suno-ai/bark#267]
Is the pronunciation of Mandarin not accurate, with a mixture of local accents and foreign intonation?

**Comment by allanwakes** [comment]
Is there any method or dataset which could be used to make bark produce mandarin more accurate, sometimes, the tone doesn't sound right.

**Comment by gkucsko** [comment]
gonna close to consolidate to here: https://github.com/suno-ai/bark/issues/222
