### ISSUE TITLE
Problem with setting temp=0.0

### ISSUE THREAD

**Issue by Aliasgarsaifee** [suno-ai/bark#270]
https://github.com/suno-ai/bark/blob/6f32532c675079a26b595e59b3d819ba470c0c91/bark/generation.py#L483

If I am setting temperature to 0.0 it is giving error, which is due to the above line in which divide by zero is happening.

Error - 
`RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`

This can be fixed by adding an epsilon=1e-9 in the denominator while dividing. which will prevent division by 0.

`probs = F.softmax(relevant_logits / (temp + epsilon), dim=-1)`

**Comment by gkucsko** [comment]
hm ya figured that's a good expected behavior since technically then it wouldn't be actually 0. curious, do you have an actual use case for a temperature this low? usually it's more in the 0.5-0.9 range

**Comment by gkucsko** [comment]
closing on inactivity. open to a PR to change this
