### ISSUE TITLE
Way to increase GPU usage?

### ISSUE THREAD

**Issue by moojustice1** [suno-ai/bark#275]
Hey everyone, 

I've been able to run bark on text and get back great results, but it only seems to use 8 gb of VRAM on my GTX 3090

Is there anyway to increase that to improve performance?

**Comment by gkucsko** [comment]
hard to improve latency without changing the architecture, but throughput could be increased by implementing batch predictions

**Comment by gkucsko** [comment]
closing in favor of https://github.com/suno-ai/bark/issues/279
