### ISSUE TITLE
How can I generate sound effects?

### ISSUE THREAD

**Issue by dellis23** [suno-ai/bark#28]
The documentation mentions being able to generate simple sound effects, but I don't see any examples of how to do this.  If I put in a prompt such as `"sound effect of a door shutting"`, I just get the voice of someone saying that, which doesn't have quite the same effect.

**Comment by Pouyanpi** [comment]
Hi @dellis23 

Per documentation it is not clear; these are something to discover. But for example 

```python
text_prompt = """
    [music by Nine Inch Nails]
"""
```
is an example that apparently works. You can try placing other relevant words within **[ ]** . Let me know if it worked.
Best,
Pi

**Comment by mcamac** [comment]
You can try

```
[door shutting]
```
as a prompt. Sometimes works better if you add more text

```
[door shutting] Hello world, that was a sound of a door shutting.
```

Caveat - this might take several generations to get something good!

**Comment by gkucsko** [comment]
Would also love to hear what sorts of things would be most useful for people here for future versions!
