### ISSUE TITLE
Getting error code at end of generation and 14s clip that is nonsense words

### ISSUE THREAD

**Issue by Marcusgeorgiadis** [suno-ai/bark#284]
I get this no matter what I do, feel like i've tried everything. using one click installer version of bark.

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\unima\Desktop\Bark_WebUI\installer_files\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\unima\Desktop\Bark_WebUI\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by C0untFloyd** [comment]
Looks like the same broken branch as in #281

**Comment by fuhuaw** [comment]
I get this no matter what I do, feel like i've tried everything. using one click installer version of bark.

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
File "C:\Users\unima\Desktop\Bark_WebUI\installer_files\env\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "C:\Users\unima\Desktop\Bark_WebUI\installer_files\env\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by fuhuaw** [comment]
A wonderful story that weaves its magic in the
child’s imagination, even while imparting an
invaluable lesson in oral health and hygiene.
This is a story that the children will return to 
time and again for a fun bedtime read.
Deep in the New Forest where no big people ever went there was a tiny little 
magical village called the Ordon Gardens. Here, three little tooth fairies 
named Incisor, Canine and Molar were busy at work in their factory. The 
three tooth fairies were all named after types of teeth.
Incisor was tall and skinny with short pink hair, Canine was also tall with blue 
hair and Molar was the short, wise one with curly, silver locks. 
All day long the busy little fairies cleaned and shined the children’s milk 
teeth they had collected during the night.

**Comment by fuhuaw** [comment]
A wonderful story that weaves its magic in the
child’s imagination, even while imparting an
invaluable lesson in oral health and hygiene.
This is a story that the children will return to 
time and again for a fun bedtime read.
Deep in the New Forest where no big people ever went there was a tiny little 
magical village called the Ordon Gardens. Here, three little tooth fairies 
named Incisor, Canine and Molar were busy at work in their factory. The 
three tooth fairies were all named after types of teeth.
Incisor was tall and skinny with short pink hair, Canine was also tall with blue 
hair and Molar was the short, wise one with curly, silver locks. 
All day long the busy little fairies cleaned and shined the children’s milk 
teeth they had collected during the night.
