### ISSUE TITLE
:grey_question:  Transform bark (30 Mo) output wav to mp3/webm (pydub)

### ISSUE THREAD

**Issue by adriens** [suno-ai/bark#288]
# :grey_question: About

i'm currently trying to compress a 30 Mo `wav` output, but `pydub` is always complaining about "error: Size should be 1, 2, 3 or 4".

# :footprints: Steps to reproduce

Below is my code sample (I built the `wav` with bark ) : 

```python
!pip install pydub
!pip install ffmpeg-python

from pydub import AudioSegment
import ffmpeg


audio = AudioSegment.from_file('/kaggle/working/auptitcafe.wav', format='wav')
audio = audio.set_sample_width(2)
# Export the audio to MP3 format
audio.export('auptitcafe.mp3', format='mp3')
```

Then I get the following error message : 

```---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
Cell In[22], line 9
      5 import ffmpeg
      8 audio = AudioSegment.from_file('/kaggle/working/auptitcafe.wav', format='wav')
----> 9 audio = audio.set_sample_width(2)
     10 # Export the audio to MP3 format
     11 audio.export('auptitcafe.mp3', format='mp3')

File /opt/conda/lib/python3.10/site-packages/pydub/audio_segment.py:1008, in AudioSegment.set_sample_width(self, sample_width)
   1003     return self
   1005 frame_width = self.channels * sample_width
   1007 return self._spawn(
-> 1008     audioop.lin2lin(self._data, self.sample_width, sample_width),
   1009     overrides={'sample_width': sample_width, 'frame_width': frame_width}
   1010 )

error: Size should be 1, 2, 3 or 4
```

**Comment by adriens** [comment]
Is there something special with bark's `wav` output ?

**Comment by C0untFloyd** [comment]
I'm unfamiliar with that module but Bark's Output Format is Mono, so perhaps try:
`audio.set_channels(1)
audio.set_sample_width(1)`

I guess it wouldn't hurt to also specify the samplerate (which is 24000).

**Comment by adriens** [comment]
Hmmmn yes, thanks, i'm giving it a try and will let you know on this issue :pray:

**Comment by dnrico1** [comment]
Are you perhaps adding a silence as per the longform audio generation notebook? Ran into the same error yesterday when doing that, because np.zeroes produced 64-bit integers (which are like 64-bit wav samples). The error says that audioop only expects wav samples with 1, 2, 3 or 4 bytes per samples which are equivalent to 8, 16, 24 or 32-bit wavs. Inserting a 64-bit silence in the middle messes things up.

**Comment by adriens** [comment]
> Are you perhaps adding a silence as per the longform audio generation notebook? R

Yes, indeed, this is how I'm adding silents. :sweat_smile: 

> The solution was to specify dtype 16bit int for the np.zeroes

Would you share some code snippets :grey_question: :pray:

**Comment by C0untFloyd** [comment]
Not the poster above but you would just specify it in np.zeroes like this:
`dtype=np.int16`

**Comment by dnrico1** [comment]
Yes exactly dtype=np.int16 as an argument to np.zeroes

**Comment by adriens** [comment]
Thanks a lot to both of you @C0untFloyd  and @dnrico1 , it really did the trick... making it possible to get the wav file into much much smaller files **without hearable quality loss** :heavy_heart_exclamation: 

```python
# Properly code slience
# https://github.com/suno-ai/bark/issues/288
silence = np.zeros(int(0.25 * SAMPLE_RATE), dtype=np.int16 )
```

| format   | size         |
|-------------|--------------|
| `.wav`     | 20.2 MB  |
| `.mp3`    | 1.7 MB    |
| `.webm` | 1.8  MB   |

**Comment by adriens** [comment]
:point_down: 

- https://github.com/suno-ai/bark/pull/305
