### ISSUE TITLE
code-switched no accent 

### ISSUE THREAD

**Issue by redaready** [suno-ai/bark#31]
For code-switched text, is it possible for BARK to not employ the native accent for each respective language in same voice?

**Comment by gkucsko** [comment]
great question, we are still experimenting a bit what the best way is for that. most commonly it will pick up an accent based on whatever language is used first. sometimes it helps to just try it a bunch of times until it happens to choose low accent, and sometimes we've also had success with special prompts like: "And for my german speaking friends: Guten Morgen." Kinda wild, but sometimes works
