### ISSUE TITLE
Reason for sounding robotic

### ISSUE THREAD

**Issue by snapo** [suno-ai/bark#34]
Hi,
I am interested in knowing why the voice output sounds so robotic.... is it because it only uses 24khz or what is causing this?

**Comment by mcamac** [comment]
Do you have a prompt/sample you can share? 24khz could definitely be one reason

**Comment by gkucsko** [comment]
pitch reason is mostly 24khz, that's a hard limit for now. in terms of audio quality it will be completely different on every generation. sometimes it will sound like a good microphone, sometimes like a bad one. to the model that's all the same
