### ISSUE TITLE
How can I uninstall this?

### ISSUE THREAD

**Issue by Devesh-N** [suno-ai/bark#343]

**Comment by JonathanFly** [comment]
You really just have delete the files, and then the models. The models can be a little hidden but on Windows there's a 90% chance you'll find them at: ```C:\Users\your_user_name\.cache\suno\bark_v0\text_2.pt``` and you can search for that text_2.pt if you can't find it there.

**Comment by Devesh-N** [comment]
> 
Hey, in that cache folder, suno folder is not present.

**Comment by russellbrown** [comment]
From the FAQs:

> "Bark uses Hugging Face to download and store models"

On my mac they saved to `~/.cache/huggingface/hub/models--suno--bark`

**Comment by Devesh-N** [comment]
> From the FAQs:
> 
> > "Bark uses Hugging Face to download and store models"
> 
> On my mac they saved to `~/.cache/huggingface/hub/models--suno--bark`

I used windows

**Comment by dpurge** [comment]
On my Windows machine I found the model in `%USERPROFILE%\.cache\suno`
I also found these and other models cached under `%USERPROFILE%\.cache\huggingface\hub`, but I think these were downloaded by other libraries. You may check `.cache` directory in your `%USERPROFILE%`.

**Comment by Devesh-N** [comment]
> %USERPROFILE%\.cache\

Thanks, it worked.
