### ISSUE TITLE
How to train this model

### ISSUE THREAD

**Issue by Toxiblevince** [suno-ai/bark#37]
This work showed us a new idea of TTS,can you tell us the method of training this model?

**Comment by gkucsko** [comment]
unfortunately our training code is too intertwined with other projects, but you can get a good idea from this great repo: https://github.com/lucidrains/audiolm-pytorch

**Comment by etmyhome** [comment]
> https://github.com/lucidrains/audiolm-pytorch

how load a custom trained model on bark ?

**Comment by Reeshark** [comment]
@etmyhome Have you loaded custom trained model (such as by AudioLM) on bark successfully?

**Comment by MohamedAliRashad** [comment]
Any updates here ?

**Comment by M-TALH007** [comment]
i want to use this model on my fyp 
in my fyp i can clone my own teacher voice can i clone and one more thing can i run this code google coolab means i want whole code with dataset to reproduce and learn the model any one tell me about these things other wise my fyp going to failure mode plz help me if anyone can known??

**Comment by M-TALH007** [comment]
> unfortunately our training code is too intertwined with other projects, but you can get a good idea from this great repo: https://github.com/lucidrains/audiolm-pytorch

sir i need help your

**Comment by yukiarimo** [comment]
Any updates?

**Comment by DrewThomasson** [comment]
Any updates?

**Comment by indexxlim** [comment]
Any updates?

**Comment by TALHA0713** [comment]
Thanks i have done thus

**Comment by zboinek** [comment]
Anyone sorted training out?

**Comment by yukiarimo** [comment]
No, it’s dead. Switch to GPT-SoVITS-V2
