### ISSUE TITLE
Running bark for the first time in pyenv downloads all the models, but second time starts download again?

### ISSUE THREAD

**Issue by chrisbward** [suno-ai/bark#373]
As titled.

I noticed the models are downloaded as blobs to ~/.cache/huggingface/hub/models--suno--bark

I wouldn't expect them to start downloading again?

**Comment by tongbaojia** [comment]
It shouldn't -- did you change the settings / the server clear the cache? 

You can always move the downloads to a different folder and save them in a persistent place.

**Comment by chrisbward** [comment]
Ah, my bad - it was the re-downloading on the fine.pt, and once that came down everything was ok.
