### ISSUE TITLE
question about emb sum in model_fine

### ISSUE THREAD

**Issue by HallidayReadyOne** [suno-ai/bark#387]
Hi, I have a question about the fine model.
When to predict the i-th quantizer codebook（pred_idx == i-1），the vall-e sum up embedding of stage 1 to i-1 as input to the model.
But in model_fine.py,    
https://github.com/suno-ai/bark/blob/599fed040e52c89e0b3580e02e2684b2c9100701/bark/model_fine.py#L123
It seems to add up 1 to i ? 
For example,  when pred_idx == 2 (to pred 3-th quantizer codebook), idx 0 to 2 (i == 1 to 3)  will be summed up?

**Comment by tongbaojia** [comment]
HI @HallidayReadyOne , I don't have great intuition here as well -- but I tried to change the `pred_idx +1` to `pred_idx`, and the generated voice is much noisier.

**Comment by tongbaojia** [comment]
But I can argue that the fine model is trained in this weird way and changing the forward now will only affect how it predicts things. I think this could be a potential bug -- let's ask @gkucsko .

**Comment by gkucsko** [comment]
Hm ya could totally be a bug thanks but ya given how it was trained it probably doesn’t help to change it. We’ve since deprecated the fine model so the next version won’t have that anyways

**Comment by HallidayReadyOne** [comment]
> But I can argue that the fine model is trained in this weird way and changing the forward now will only affect how it predicts things. I think this could be a potential bug -- let's ask @gkucsko .

Hi tongbao. I think so. Cause changing from pred_idx+1 to pred_idx leads to worse results.

**Comment by HallidayReadyOne** [comment]
> Hm ya could totally be a bug thanks but ya given how it was trained it probably doesn’t help to change it. We’ve since deprecated the fine model so the next version won’t have that anyways

Hi Georg. One thing may needs to be confirmed, is the training also carried out in this mode? Thx

**Comment by gkucsko** [comment]
yup training was done with the same logic

**Comment by HallidayReadyOne** [comment]
> yup training was done with the same logic

Thanks for your reply, this issue will be closed.
