### ISSUE TITLE
GH repo is MIT but the HF demo shows non-commercial license

### ISSUE THREAD

**Issue by aniketmaurya** [suno-ai/bark#396]
Please help me understand what is commercially licensed for Bark?

![image](https://github.com/suno-ai/bark/assets/21018714/ae9a3b74-f5aa-4843-bfbb-04a776b7c92a)

**Comment by gkucsko** [comment]
Thanks, that’s outdated, bark isn’t MIT :)

**Comment by mcamac** [comment]
*Bark is now MIT

**Comment by aniketmaurya** [comment]
> Thanks, that’s outdated, bark isn’t MIT :)

Then shouldn't the code license file be updated? It is confusing and I believe you can't stop people using it commercially if you keep the MIT license in the source code.

**Comment by mcamac** [comment]
Sorry, that was a typo from @gkucsko  - Bark is MIT  (as per the license) and available for commercial use

**Comment by aniketmaurya** [comment]
thank you for the clarification @mcamac  🙌🏼
