### ISSUE TITLE
Chirp?

### ISSUE THREAD

**Issue by benedlore** [suno-ai/bark#400]
Is chirp a separate model or is it currently unreleased? Or is it a certain configuration of bark that is proprietary?

**Comment by aiwusheMYP** [comment]
Huh-ha
Hey
Hey yeah, hey
指切りげんまん ホラでも吹いたら
針でもなんでも 飲ませていただき Monday
It doesn't matter if it's Sunday

**Comment by sirinath** [comment]
Have the same question.

**Comment by AbdullahMustafa040** [comment]
@JonathanFly i have the same question

**Comment by benedlore** [comment]
From what I can tell it is proprietary and I have not seen them make any public statement about releasing the model as they did with bark (or workflow, or however it is done).

**Comment by AbdullahMustafa040** [comment]
ok 
according to research (based on discord). chirp is separate model. but now in alpha testing. will see if they public

**Comment by JonathanFly** [comment]
> Is chirp a separate model or is it currently unreleased? Or is it a certain configuration of bark that is proprietary?

Chirp is a separate model currently only running in the Discord, as a bot. Chirp V2 is out soon, with support for genre guidance and more languages. 

As far as a public release, on Discord one of the Suno devs was asked "will the Chirp code be released on gitlab like Bark so we can run it ourselves?" and responded "unfortunately not on release at least. maybe in the future we can figure something out but for now will be on discord only."

**Comment by benedlore** [comment]
Alright, I think that pretty much answers it. Thanks, apprec.

**Comment by drvpn** [comment]
A good compromise, in between open sourcing Chirp, so users can run their own servers, and keeping it closed source / proprietary would be opening up an API.  This way everyone can participate and Suno AI still gets paid.  Hosting inference is complex and expensive. Once developers start using your API to embed Chirp features into applications your API revenues will soar.  Just a thought, great product! :)
