### ISSUE TITLE
how to set The attention mask and the pad token id  ?

### ISSUE THREAD

**Issue by yangboz** [suno-ai/bark#402]
```
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:10000 for open-end generation.
```

any idea?
thanks for your great work.

**Comment by tongbaojia** [comment]
Hi @yangboz 

These are generated from the transformers library and don't appear to correlate directly to what bark has. Could you provide more context and code on how you ran into this warning?

**Comment by yangboz** [comment]
codebase  from  git clone bark ,  env py3.9, pip install . from  https://github.com/suno-ai/bark

then test basic  func, as following:
```
from transformers import AutoProcessor, BarkModel


hgmodelname="suno/bark-small"
processor = AutoProcessor.from_pretrained(hgmodelname)
model = BarkModel.from_pretrained(hgmodelname)

voice_preset = "v2/en_speaker_1"

inputs = processor("Hello, my dog is cute", voice_preset=voice_preset)

audio_array = model.generate(**inputs,pad_token_id=100)
audio_array = audio_array.cpu().numpy().squeeze()
```
after huggleface model download successfully. run it  then warning continued.

**Comment by tongbaojia** [comment]
> 

How did you install transformers? I don't have BarkModel on transformers -- and I don't think it should, that's a hugging face lib.

`ImportError: cannot import name 'BarkModel' from 'transformers'`

**Comment by yangboz** [comment]
> How did you install transformers? I don't have BarkModel on transformers -- and I don't think it should, that's a hugging face lib.
> 
> `ImportError: cannot import name 'BarkModel' from 'transformers'`

try ```pip install git+https://github.com/huggingface/transformers.git```

**Comment by chengxiaochuan** [comment]
@yangboz I also encountered the same issue. Have you resolved this problem? If yes, how did you solve it?

**Comment by yangboz** [comment]
> @yangboz I also encountered the same issue. Have you resolved this problem? If yes, how did you solve it?

not yet ,I have tried it both MBP and ubuntu . may it is transformer related, I will dig it more ,

**Comment by sanchit-gandhi** [comment]
Feel free to open an issue in the `transformers` repository @yangboz to better track this! (since the behaviour is derived from the `transformers` implementation of Bark rather than the Suno AI one). Also cc @ylacombe

**Comment by mkosecki** [comment]
I think this is done on purpose, the information is from HF but in the code there is:

```
kwargs_semantic = {
            # if "attention_mask" is set, it should not be passed to CoarseModel and FineModel
            "attention_mask": kwargs.pop("attention_mask", None)
```

So one way is to just suppress this warning. With batch the attentions will look at the padding, so the unexpected behaviour may occur.
 And that the pad_token is set to eos_token is something that is necessary for open-end generation 'cos that is how bark works. It generates tokens until some number of steps is reached.

**Comment by borboto** [comment]
Was anyone able to sort this out? I've just came across the same issue.

**Comment by sanchit-gandhi** [comment]
cc @ylacombe

**Comment by yangboz** [comment]
maybe it can be fixed with git clone and pull  thelatest codebase from  the  repository of  transformer in huggleface, then pip install .

**Comment by ssu-art** [comment]
```
from transformers import AutoProcessor, BarkModel
from scipy.io.wavfile import write as write_wav

processor = AutoProcessor.from_pretrained("suno/bark")
model = BarkModel.from_pretrained("suno/bark")

voice_preset = "v2/en_speaker_6"
text = "Hello, my dog is cute"
inputs = processor(text, voice_preset=voice_preset, return_tensors="pt", padding=True)

# add attention mask here
attention_mask = inputs["attention_mask"]

outputs = model.generate(
  input_ids=inputs["input_ids"], 
  attention_mask=attention_mask,
  
  # add pad token id here
  pad_token_id=processor.tokenizer.pad_token_id
)

audio_array = audio_array.cpu().numpy().squeeze()

# save audio to disk, but first take the sample rate from the model config
sample_rate = model.generation_config.sample_rate
write_wav("bark_generation_result.wav", sample_rate, audio_array)
```

**Comment by celsowm** [comment]
> ```
> from transformers import AutoProcessor, BarkModel
> from scipy.io.wavfile import write as write_wav
> 
> processor = AutoProcessor.from_pretrained("suno/bark")
> model = BarkModel.from_pretrained("suno/bark")
> 
> voice_preset = "v2/en_speaker_6"
> text = "Hello, my dog is cute"
> inputs = processor(text, voice_preset=voice_preset, return_tensors="pt", padding=True)
> 
> # add attention mask here
> attention_mask = inputs["attention_mask"]
> 
> outputs = model.generate(
>   input_ids=inputs["input_ids"], 
>   attention_mask=attention_mask,
>   
>   # add pad token id here
>   pad_token_id=processor.tokenizer.pad_token_id
> )
> 
> audio_array = audio_array.cpu().numpy().squeeze()
> 
> # save audio to disk, but first take the sample rate from the model config
> sample_rate = model.generation_config.sample_rate
> write_wav("bark_generation_result.wav", sample_rate, audio_array)
> ```

BarkProcessor._validate_voice_preset_dict() got an unexpected keyword argument 'padding'

**Comment by nnilayy** [comment]
Well, its indeed a warning coming from the transformers library. The issue is that the `model.generate()` function doesn't receive the attention masks along with the input_ids. That is because `inputs = tokenizer.encode(prompt)` returns just the input_ids but not the attention mask. To solve this just use `inputs = tokenizer(prompt)`,  which returns both the input_ids and the attention mask.

So if you replace this code
```
inputs = tokenizer.encode(prompt)
output = model.generate(inputs)
```
With this

```
inputs = tokenizer(prompt)
output = model.generate(**inputs)
```
The error warning goes away. Hope that helps 😊.

**Comment by nauen** [comment]
not sure why this got closed. There were no solution for me here.

This script I was able to run:
`
from transformers import AutoProcessor, BarkModel
from scipy.io.wavfile import write as write_wav

processor = AutoProcessor.from_pretrained("suno/bark")
model = BarkModel.from_pretrained("suno/bark")

text = "Good Morning"
inputs = processor(text, return_tensors="pt")

attention_mask = inputs["attention_mask"]

audio_array = model.generate(
  input_ids=inputs["input_ids"], 
  attention_mask=attention_mask,
  pad_token_id=processor.tokenizer.pad_token_id
)

audio_array = audio_array.cpu().numpy().squeeze()

sample_rate = model.generation_config.sample_rate
write_wav("bark_generation_result.wav", sample_rate, audio_array)
`

**Comment by Shreyan1** [comment]
Got the same issue while using Whisper Model from hugging face - 

```
import os
import warnings
warnings.filterwarnings('ignore')  # Suppress all other warnings
os.environ['TRANSFORMERS_VERBOSITY'] = 'error'  # Suppress transformer warnings

from transformers import pipeline

model = pipeline("automatic-speech-recognition", 
                 model="openai/whisper-tiny.en")

transcription = model("<>.wav")
print(transcription["text"])
```

So I have been suppressing the Transformers Verbosity to not show  the ATTENTION MASK issue.

If anyone gets a proper fix, please let me know !

**Comment by CircleAAA** [comment]
Is there a way to at least suppress the warning?
