### ISSUE TITLE
How can I save an audio file using the long audio generation technique provided in your notebooks?

### ISSUE THREAD

**Issue by MinervaArgus** [suno-ai/bark#404]

**Comment by MinervaArgus** [comment]
def tts(script):
    model = preload_models()
    nltk.download('punkt')
    sentences = nltk.sent_tokenize(script)
    silence = np.zeros(int(0.25 * SAMPLE_RATE))
    pieces = []
    for sentence in sentences:
        audio_array = generate_audio(sentence)
        pieces += [audio_array, silence.copy()]
    with open("audio_file.wav", "wb") as file:
        file.write(np.concatenate(pieces))

This is my current code and it saves the file but is unreadable and cannot be played. It says it is because of the .wav format but I don't know what else to save it as

**Comment by himanshupphp** [comment]
> def tts(script): model = preload_models() nltk.download('punkt') sentences = nltk.sent_tokenize(script) silence = np.zeros(int(0.25 * SAMPLE_RATE)) pieces = [] for sentence in sentences: audio_array = generate_audio(sentence) pieces += [audio_array, silence.copy()] with open("audio_file.wav", "wb") as file: file.write(np.concatenate(pieces))
> 
> This is my current code and it saves the file but is unreadable and cannot be played. It says it is because of the .wav format but I don't know what else to save it as

Hello there, 
add these lines to your code and it'll start working hope this helps you.

```
genAudio = Audio(np.concatenate(pieces), rate=SAMPLE_RATE)
with open("audio_file.wav", "wb") as file:
  file.write(genAudio.data)
```

**Comment by vembarrajan** [comment]
The following code will save the audia as - fileName.wav. 

`from scipy.io.wavfile import write as write_wav
write_wav("fileName.wav", SAMPLE_RATE, np.concatenate(pieces))`
