### ISSUE TITLE
DO NOT DISRESPECT MY COUNTRY

### ISSUE THREAD

**Issue by NxRoot** [suno-ai/bark#442]
THIS IS NOT PORTUGUESE LANGUAGE 🇵🇹! 
ITS BRAZILIAN LANGUAGE, REPLACE THE FLAG FOR THE BRAZILIAN FLAG 🇧🇷

<img src="https://i.ibb.co/SmtFXQq/Screenshot-2023-08-28-at-14-40-01.png"/>

This is disrespect for my country!

**Comment by kmfreyberg** [comment]
Fixed — thanks for flagging, @NxRoot 🙏
