### ISSUE TITLE
Stuck on Preloading Models step

### ISSUE THREAD

**Issue by Unforgivenmind** [suno-ai/bark#446]
The installation gets stuck on Preloading Models step.
![Screenshot_512](https://github.com/suno-ai/bark/assets/106400709/72bda076-6247-47c8-a90e-3b7693a97b1d)

**Comment by tongbaojia** [comment]
Seems like a internet connection issue see #317 or #197 

TLDR:
You can try to download the .pt files from huggingface directly:
https://huggingface.co/suno/bark/tree/main
and put them into the models folder.
