### ISSUE TITLE
AttributeError: 'GenerationConfig' object has no attribute 'semantic_config'

### ISSUE THREAD

**Issue by yangboz** [suno-ai/bark#450]
```
bark/transformers/src/transformers/models/bark/modeling_bark.py", line 1516, in generate
    semantic_generation_config = BarkSemanticGenerationConfig(**self.generation_config.semantic_config)
AttributeError: 'GenerationConfig' object has no attribute 'semantic_config'
```

any idea?

**Comment by 19samira93** [comment]
A b c d e f g h I j k l m n o p

**Comment by wanglg007** [comment]
this issue has solved?

**Comment by wanglg007** [comment]
![image](https://github.com/suno-ai/bark/assets/40556406/70fd2e53-69e8-466e-a00d-08bea870b197)

python 3.8

**Comment by JonathanFly** [comment]
It's a HuggingFace transformers question really, not the official Suno Bark repo. You might just need to update transformers. For a quick example maybe look at: https://github.com/ylacombe/explanatory_notebooks/blob/main/hf_bark_long_text_generation.py

**Comment by IronSpiderMan** [comment]
i meet the same issue when i use bark locally. There no error about missing file, but when i put the generation_config.json..etc files in the local path, and it's works.

**Comment by Cazforshort** [comment]
> i meet the same issue when i use bark locally. There no error about missing file, but when i put the generation_config.json..etc files in the local path, and it's works.

Can you walk me through that solution please? I'm running into the same problem with Transfomers.

**Comment by IronSpiderMan** [comment]
> > i meet the same issue when i use bark locally. There no error about missing file, but when i put the generation_config.json..etc files in the local path, and it's works.
> 
> Can you walk me through that solution please? I'm running into the same problem with Transfomers.

have you tried to download those files from suno/bark, and put it in your local cache Folder.

**Comment by yangboz** [comment]
> > > i meet the same issue when i use bark locally. There no error about missing file, but when i put the generation_config.json..etc files in the local path, and it's works.
> > 
> > 
> > Can you walk me through that solution please? I'm running into the same problem with Transfomers.
> 
> have you tried to download those files from suno/bark, and put it in your local cache Folder.

could you share it's url with me? thanks.
