### ISSUE TITLE
Can somebody guide me? Bark doesn't Bark after pytorch version update.

### ISSUE THREAD

**Issue by ChamathDilanka** [suno-ai/bark#453]
As instructions per [https://github.com/suno-ai/bark#-installation](https://github.com/suno-ai/bark#-installation) I had been able to setup bark locally in my laptop and run it. I kept consuming much time to produce results and gave a warning saying "No GPU being used. Careful, inference might be very slow!".

Yes I've tried loading small models and "os.environ["SUNO_USE_SMALL_MODELS"] = "True"" before entering to next step.

So I went on researching again and as suggested in [https://github.com/suno-ai/bark/issues/202](https://github.com/suno-ai/bark/issues/202) went on and updated pytorch version.

After pytorch update it keeps giving me error saying "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 380.00 MiB (GPU 0; 2.00 GiB total capacity; 1.42 GiB already allocated; 83.07 MiB free; 1.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF".

I again tried with loading small models as per many other previous issues mentioned.

My GPU details as following:
**NVIDIA GeForce MX330
_CudaDeviceProperties(name='NVIDIA GeForce MX330', major=6, minor=1, total_memory=2047MB, multi_processor_count=3)
(6, 1)**

Current pytorch version : 
2.0.1+cu117

Can someone please give me some help to resolve this issue? It will be really helpful sine I'm really new to this!

Thanks and Regards!

**Comment by JonathanFly** [comment]
In `generation.py` you can try adding `model = model.half()` to `_load_model()`
```
def _load_model(ckpt_path, device, use_small=False, model_type="text"):
    if model_type == "text":
        ConfigClass = GPTConfig
        ModelClass = GPT
    elif model_type == "coarse":
        ConfigClass = GPTConfig
        ModelClass = GPT
    elif model_type == "fine":
        ConfigClass = FineGPTConfig
        ModelClass = FineGPT
    else:
        raise NotImplementedError()
    model_key = f"{model_type}_small" if use_small or USE_SMALL_MODELS else model_type
    model_info = REMOTE_MODEL_PATHS[model_key]
    if not os.path.exists(ckpt_path):
        logger.info(f"{model_type} model not found, downloading into `{CACHE_DIR}`.")
        _download(model_info["repo_id"], model_info["file_name"])
    checkpoint = torch.load(ckpt_path, map_location=device)
    # this is a hack
    model_args = checkpoint["model_args"]
    if "input_vocab_size" not in model_args:
        model_args["input_vocab_size"] = model_args["vocab_size"]
        model_args["output_vocab_size"] = model_args["vocab_size"]
        del model_args["vocab_size"]
    gptconf = ConfigClass(**checkpoint["model_args"])

    ## add the next line
    model = model.half()
    ```

If you make sure cpu offloading is on you can even use large models in 2GB, though it can be tight if Windows is using a lot of memory.

You can also look the huggingface version: [https://huggingface.co/blog/optimizing-bark](https://huggingface.co/blog/optimizing-bark)

**Comment by ChamathDilanka** [comment]
@JonathanFly  thank you very much for the tip.

Tried your suggestion. But unfortunately error starts from below line.

"checkpoint = torch.load(ckpt_path, map_location=device)" (Line 212 in generation.py)

Will try your next suggestion.

**Comment by JonathanFly** [comment]
> (Line 212 in generation.py)
> 
> Will try your next suggestion.

My mistake, I wasn't copying and pasting real code I just did on the fly and put it on the wrong line, it's off by one:
```
    gptconf = ConfigClass(**checkpoint["model_args"])
    model = ModelClass(gptconf)

    # whoops add it here I mean
    model = model.half()
    
    state_dict = checkpoint["model"]
    # fixup checkpoint
    unwanted_prefix = "_orig_mod."
    ```

**Comment by ChamathDilanka** [comment]
@JonathanFly Thank you again for fast reply! Glad someone genuinely tries to help.

Unfortunately your last suggested change also didn't work for me.

Trying out steps as per this video - https://www.youtube.com/watch?v=tvH_n-vwUA0

So far it works!
