### ISSUE TITLE
Many voices in same output wav

### ISSUE THREAD

**Issue by michaeltran33** [suno-ai/bark#454]
The output wav has many voices in it. Tried with several lines -> many voices. Put everything in one line - no line break - -> many voices and tones. Is there anyone having same problem?

**Comment by JohnHunkler** [comment]
I can mitigate this somewhat by adding a specific history voice and setting it to use an old generation.  Here's how I did it using the Webui.

Put in a fairly long prompt.  about 10 - 15 seconds of speech.  Generate 9 outputs.

Then go listen to each output.  Choose the one you like best and click use as history.

This seems to keep the voice pretty consistent across generations, particularly if you use one long text prompt, even if its broken up by bark.

**Comment by Rqcker** [comment]
@JohnHunkler Hi, I am having the same issue. Have you tried debugging(using history) under CLI? How should I do it?

**Comment by JohnHunkler** [comment]
What you need to do is enable the "use old generation as history"  That
helps stabilize it somewhat.
