### ISSUE TITLE
Is there a fork that allows quicker inference on cpu?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [suno-ai/bark#466]
See title.

**Comment by JonathanFly** [comment]
Right now only a little quicker, but maybe much quicker eventually https://github.com/PABannier/bark.cpp

**Comment by ErfolgreichCharismatisch** [comment]
> Right now only a little quicker, but maybe much quicker eventually https://github.com/PABannier/bark.cpp

Cheers man, just what I was looking for.

**Comment by JonathanFly** [comment]
> > Right now only a little quicker, but maybe much quicker eventually https://github.com/PABannier/bark.cpp
> 
> Cheers man, just what I was looking for.

One more you may want to explore: https://github.com/intel-analytics/BigDL/pull/9016
