### ISSUE TITLE
Can I add assets prompts maded by myself?

### ISSUE THREAD

**Issue by kostya-sec** [suno-ai/bark#48]
If I want to add new assets prompts, how can I fine-tune them? Or import new prompts files generated from other libraries?

**Comment by gkucsko** [comment]
we now support saving generated outputs (via `output_full` and then `save_as_prompt`). after that you can pass the location of the npz files in as `history_prompt`

**Comment by kostya-sec** [comment]
You're welcome. If I want to train a completely new voice using new voice data. , such as an entirely new young girl's voice or an elderly person's voice, how should I do it?

**Comment by gkucsko** [comment]
sorry right now we don't support custom voices like that due to potential misuse. it has to be an artifical model-created output that can then be further used

**Comment by Straafe** [comment]
So you can essentially re-roll random voices as much as you want and save those you like? Maybe there can be some basic, general controls for voices? So you still could not do anything close to voice cloning, but had some basic control.
