### ISSUE TITLE
Chinese prompt generate failed.

### ISSUE THREAD

**Issue by dtx525942103** [suno-ai/bark#5]
how to input chinese?

**Comment by gkucsko** [comment]
Should be as simple as using a Chinese character text (simplified). Maybe try again? What text are you using?

**Comment by dtx525942103** [comment]
text_prompt = "床前明月光，疑似地上霜"
print(datetime.datetime.now())
print(text_prompt)
audio_array = generate_audio(text_prompt, history_prompt="speech_0")
save_wav("4.wav", SAMPLE_RATE, audio_array)
print(datetime.datetime.now())

**Comment by dtx525942103** [comment]
i find bark has some update

**Comment by gkucsko** [comment]
Try without a history prompt since that‘s in English I believe. We also just added multilingual prompts earlier today so if you pull you should be able to use zh_speaker_0-9
