### ISSUE TITLE
Installation error: Something went wrong

### ISSUE THREAD

**Issue by hritikb27** [suno-ai/bark#50]
I am getting this same error on my local system as well as here in collab notebook.

![barkError](https://user-images.githubusercontent.com/86529959/233781579-8934b779-34f6-42e4-84b8-8573e774e98d.PNG)

**Comment by przdev** [comment]
same with me

**Comment by shengkaixuan** [comment]
met the same error, just rerun the code the error is gone, may be it is the network.

**Comment by gkucsko** [comment]
yeah, probably a temporary network issue. we use cloudflare but things can always happen. if you just re-run it should automatically fix borked models. feel free to reopen if still issues
