### ISSUE TITLE
Add my/your voices to the dataset

### ISSUE THREAD

**Issue by xnousnow** [suno-ai/bark#52]
I would like to enrich the dataset by adding my voice to the dataset, I would appreciate it if you provide information on how to participate in that.

**Comment by gkucsko** [comment]
very interesting idea to have opt-in allowed voice cloning. would you be willing to give your voice to the community? we can try to look into how that's most easily doable if you want

**Comment by xnousnow** [comment]
As a Korean speaker, I can confirm that the Korean dataset is relatively smaller compared to other datasets. Therefore, I am willing to contribute my voice to help improve it.
