### ISSUE TITLE
Need written documentation?

### ISSUE THREAD

**Issue by ritosubhra** [suno-ai/bark#53]
I've observed many members want documentations on Suno-ai. 

Please comment your requirements below, I'll try to write to the best of my knowledge.

**Comment by MaestroT** [comment]
Yes, I would like to have a documentation. And I'd like to know how to generate clean speech, speech with background noise, purely sound effects and how to save the generate audio to a wav file.

**Comment by sgreenb** [comment]
Documentation on this chunk:
```
def generate_audio(text, voice_name):
     # generation with more control
     from bark.generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
     x_semantic = generate_text_semantic(
     text_prompt,
     history_prompt=voice_name,
     temp=0.7,
     top_k=50,
     top_p=0.95,
     )

     x_coarse_gen = generate_coarse(
     x_semantic,
     history_prompt=voice_name,
     temp=0.7,
     top_k=50,
     top_p=0.95,
     )
     x_fine_gen = generate_fine(
     x_coarse_gen,
     history_prompt=voice_name,
     temp=0.5,
     )
     audio_array = codec_decode(x_fine_gen)
```

As well as more detail on how to actually do the voice cloning. The clone_voice.ipynb has some code, but it also has comments like this:

```
# the audio you want to clone (will get truncated so 5-10 seconds is probably fine, existing samples that I checked are around 7 seconds)
```

Which would indicate that the person who wrote it doesn't really understand what they're doing, after all, why are they basing it on samples they saw? And where is it getting truncated? And how is 7 seconds anywhere close to enough training data for a new voice model?
