### ISSUE TITLE
CUDA out of memory. Tried to allocate 508.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes is free

### ISSUE THREAD

**Issue by hritikb27** [suno-ai/bark#55]
![barkError](https://user-images.githubusercontent.com/86529959/233794994-43e4a6cf-4ebc-4f09-8519-39ff48ada0a6.PNG)

**Comment by Aryan-Deshpande** [comment]
Could you show a snippet of your Python file from where your error is originating.

**Comment by hritikb27** [comment]
@Aryan-Deshpande  yes, here:
![barkError](https://user-images.githubusercontent.com/86529959/233799985-ca5ceb1b-8a3a-4caf-8148-2adfa0e80c04.PNG)

**Comment by gkucsko** [comment]
added some new options today to load smaller versions of model more flexibly, see here: https://github.com/suno-ai/bark/issues/51
