### ISSUE TITLE
Possible missing deps in installation instructions?

### ISSUE THREAD

**Issue by RickCarlino** [suno-ai/bark#56]
# The Issue

I believe the installation instructions may not fully describe the dependencies required to install the library. My guess is that there could be some common dependencies that many Python developers use so frequently that they were unintentionally omitted from the installation instructions.

I attempted to run the example script in the README.md on both a Windows and Ubuntu machine. Unfortunately, it failed both times due to missing dependencies.

For some background, I don't usually use Python or Pip for my day-to-day development work. I installed both from scratch and followed the installation instructions word-for-word since I'm not typically a Python developer.

The example failed to load on both Windows and Ubuntu.

# Steps to Reproduce

I'll run the repro steps in a Docker container because it makes it easier for others to reproduce the steps on their local machine. Although I don't plan to actually run Bark in Docker, it's useful for creating a reproduction of the error.

## Provision a Machine to Test Things On

First, let's get an Ubuntu 22 machine running (I ran this in Fish, Bash users might need to adjust the script):

```fish
docker run --rm -it -v (pwd):/data ubuntu bash
```

Then we can verify the Ubuntu version:

```shell
root@9269e48a1db8:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

## Install Deps

Now we'll install Python, Pip, Git, and Bark. I'm also going to install `nano` to make it easier to copy and paste the example from the README into the container.

```
apt update
apt install python-is-python3 python3-pip git nano --yes
```

## Install Bark

OPTION 1: PIP Installation

```
pip install git+https://github.com/suno-ai/bark.git
```

Yields:

```
Collecting git+https://github.com/suno-ai/bark.git
  Cloning https://github.com/suno-ai/bark.git to /tmp/pip-req-build-3d5bs4cx
  Running command git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git /tmp/pip-req-build-3d5bs4cx
  Resolved https://github.com/suno-ai/bark.git to commit 874af1bae9a74324b1fff5573963373c0016f0e0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=7276 sha256=dfc2d55c1364d743af2968153c439788ee12364a281e9c354d5a9e84870d99e4
  Stored in directory: /tmp/pip-ephem-wheel-cache-hvvpy6mf/wheels/e6/6d/c2/107ed849afe600f905bb4049a026df3c7c5aa75d86c2721ec7
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

OPTION 2: Git Clone Installation

```
git clone https://github.com/suno-ai/bark
cd bark && pip install .
```

Yields:

```
Cloning into 'bark'...
remote: Enumerating objects: 280, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 280 (delta 42), reused 28 (delta 19), pack-reused 219
Receiving objects: 100% (280/280), 1.34 MiB | 4.02 MiB/s, done.
Resolving deltas: 100% (70/70), done.
Processing /bark
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=7276 sha256=f8d1e0b5666bfda15fc921b10a2169365a43918a66adf1dbb8514119992c0855
  Stored in directory: /tmp/pip-ephem-wheel-cache-ntwrhv92/wheels/de/02/45/2e72ff30ce0400df4bc80201420b614232aa3ff723e67fc622
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

## Run Example

```
touch example.py
nano example.py # Paste the example here.
python example.py
```

## The Error

I had different issues on Windows, but I unfortunately did not save the results (my Windows machine also had a fresh Pip/Python install).

Here is the error I got when building from Git cloned source:

```
root@42717c6cb118:/bark# python example.py 
Traceback (most recent call last):
  File "/bark/example.py", line 1, in <module>
    from bark import SAMPLE_RATE, generate_audio
  File "/bark/bark/__init__.py", line 1, in <module>
    from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
  File "/bark/bark/api.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

And the error when installing via the `pip install git+...` method:

```
Traceback (most recent call last):
  File "//example.py", line 1, in <module>
    from bark import SAMPLE_RATE, generate_audio
ModuleNotFoundError: No module named 'bark'
```

# Conclusion

It appears that there are some missing steps or dependencies in the installation instructions. Please let me know if there's any other information I can provide to help find a resolution to this issue.

**Comment by gkucsko** [comment]
can you do `pip install ipython` and run the example in the interactive shell?

**Comment by RickCarlino** [comment]
Hi @gkucsko Thanks for helping me look into this issue.

When I install via PIP:

```
root@09855d705e3f:/# ipython
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
   ...: 
   ...: from bark import SAMPLE_RATE, generate_audio, preload_models
   ...: from IPython.display import Audio
   ...: 
   ...: # download and load all models
   ...: preload_models()
   ...: 
   ...: # generate audio from text
   ...: text_prompt = """
   ...:      Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
   ...:      But I also have other interests such as playing tic tac toe.
   ...: """
   ...: audio_array = generate_audio(text_prompt)
   ...: 
   ...: # play text in notebook
   ...: Audio(audio_array, rate=SAMPLE_RATE)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from bark import SAMPLE_RATE, generate_audio, preload_models
      2 from IPython.display import Audio
      4 # download and load all models

ModuleNotFoundError: No module named 'bark'
```

When I install from source (seems to get farther this way):

```
root@09855d705e3f:/bark# ipython
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
   ...: 
   ...: from bark import SAMPLE_RATE, generate_audio, preload_models
   ...: from IPython.display import Audio
   ...: 
   ...: # download and load all models
   ...: preload_models()
   ...: 
   ...: # generate audio from text
   ...: text_prompt = """
   ...:      Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
   ...:      But I also have other interests such as playing tic tac toe.
   ...: """
   ...: audio_array = generate_audio(text_prompt)
   ...: 
   ...: # play text in notebook
   ...: Audio(audio_array, rate=SAMPLE_RATE)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from bark import SAMPLE_RATE, generate_audio, preload_models
      2 from IPython.display import Audio
      4 # download and load all models

File /bark/bark/__init__.py:1
----> 1 from .api import generate_audio, text_to_semantic, semantic_to_waveform, save_as_prompt
      2 from .generation import SAMPLE_RATE, preload_models

File /bark/bark/api.py:3
      1 from typing import Optional
----> 3 import numpy as np
      5 from .generation import codec_decode, generate_coarse, generate_fine, generate_text_semantic
      8 def text_to_semantic(
      9     text: str,
     10     history_prompt: Optional[str] = None,
     11     temp: float = 0.7,
     12     silent: bool = False,
     13 ):

ModuleNotFoundError: No module named 'numpy'
```
If I run `pip install numpy`, the error goes away and generates a new error: `ModuleNotFoundError: No module named 'requests'`

**Comment by gkucsko** [comment]
looks like you didn't install properly if you can't import bark. what pip command did you run? did you maybe change venv?

**Comment by RickCarlino** [comment]
@gkucsko the only commands I ran were the ones listed, and I did so on a fresh Ubuntu container each time to eliminate the possibility of bad installation files. These errors were similar to the errors seen when I tried on a fresh Python install on a non-docker Ubuntu setup / Windows 10. Were you able to install the lib from a clean distro or windows machine? If so, did you install any tools not listed in the README file? The only steps I followed were those in the readme or in the repro steps above.

**Comment by gkucsko** [comment]
hmm, not sure sorry. you might wanna have a look in the discord channel. lots of people with different setups are talking about how to get everything up and running there

**Comment by ImLunaHey** [comment]
Hit the same issue here. I'm on macOS for what it's worth.

**Comment by ImLunaHey** [comment]
Found the issue. Use `pip3` for the install and make sure to also install iPython.


It's all working after I did this.
```
pip3 install git+https://github.com/suno-ai/bark.git
pip3 install ipython
```

**Comment by gkucsko** [comment]
that probably means you have your environments a bit messed up. ideally you want to use virtual environments where pip and pip3 refer to the same underlying python install

**Comment by ImLunaHey** [comment]
@gkucsko I think you'll find this is how a lot of people have their env setup. 

From what I've seen myself from other devs who had python installed before v3 came out. `python3` and `pip3` point to v3 and then `python` and `pip` point to v2.

Also keep in mind I'm not someone that uses python regularly so this would be different to people who DO use it daily which I'm guessing is the case for yourself and the other devs that put these instructions together.

**Comment by gkucsko** [comment]
of course ya, thanks for finding the reason and sharing with the community. agreed our install instructions are pretty bad for now :/

**Comment by dobladov** [comment]
I was able to make it run on Mac using `virtualenv` in case it helps someone else.
```sh
git clone https://github.com/suno-ai/bark
cd bark
virtualenv venv
source venv/bin/activate
pip install .
pip3 install ipython
python3 ./test.py //  file with the basic example  https://github.com/suno-ai/bark#-basics
```

**Comment by RickCarlino** [comment]
Thanks @dobladov I finally had time to check and it does indeed fix my issue. I just proposed a PR that will add this information to the README.
