### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by CopyNinja1999** [suno-ai/bark#6]
@gkucsko Thanks for such an amazing work！
Could you please share some data examples (like 5 items) to show how you construct the dataset? I am quite curious how you manipulate with the [laughs], [humm] tokens or music descriptors. Thanks in advance.
would you mind writing a more specific technical report?
Also the audio generated by the notebook is not as good as the demo shows. Do you have a larger pretrained model?

**Comment by gkucsko** [comment]
Thanks, great to hear. The data formatting is similar to what you see in closed captions. We try to add as much diversity in formatting as possible but a lot of it we are also still discovering ourselves in regards to what gets learned by the model efficiently. 
Happy to post some more details in the future, blog post paper etc if useful to the community.
We do have some larger models that are a bit slow to run on things like colab. We plan to make them accessible in our Studio in the near future to make things easier. All of the samples you see in the repo however were made with the public versions of the models. Maybe try playing with the text, the prompts (especially meta tags can be a bit fickle) and also sometimes it takes a few tries to get exactly what you want. We are still exploring to to best guide the generation through good prompt engineering. Hope that helps

**Comment by CopyNinja1999** [comment]
> 

Thanks. Looking forward to your new posts!
