### ISSUE TITLE
13 second limit?

### ISSUE THREAD

**Issue by 7gxycn08** [suno-ai/bark#60]
How do you unlock the limit?

**Comment by wsippel** [comment]
There's nothing to unlock - it's a limitation of the model itself, not an arbitrary limit. To generate longer audio, you can split the input, generate audio chunk by chunk, then join the individual chunks. That's how I've implemented it in the Oobabooga extension.

**Comment by gkucsko** [comment]
yup! people are writing great little tools to stitch things together. also see https://github.com/suno-ai/bark/issues/21
