### ISSUE TITLE
How do you get the same voice?

### ISSUE THREAD

**Issue by TheCompAce** [suno-ai/bark#69]
How do you get the same voice?

I used "MALE:" but every time it is another voice. Do you have a "value" you can pass to the AI for "seed"? I understand this is just a start.

**Comment by David-Krug** [comment]
Look at the ReadMe at:
[https://github.com/suno-ai/bark#-voice-presets-and-voiceaudio-cloning](https://github.com/suno-ai/bark#-voice-presets-and-voiceaudio-cloning)

You can specify the voice in the generate_audio function.

**Comment by gkucsko** [comment]
yeah, try using `history_prompt` with a specific speaker. some might work better than others for voice consistency

**Comment by rhpo** [comment]
Hey @TheCompAce,

You can specify a constant voice for generation using the ``history_prompt`` parameter in the ``generate_audio`` function...
The pattern is ``{lang_code}_speaker_{0-9}``

Example:
``audio_array = generate_audio(text_prompt, history_prompt="en_speaker_1")``

It has been mentionned in the documentation !

**Comment by TheCompAce** [comment]
OK thanks, maybe the project's head will take these questions and have ChatGPT make a readme file for them.

**Comment by gkucsko** [comment]
hahaha, i'll give it a try lol

**Comment by hritikb27** [comment]
> Hey @TheCompAce,
> 
> You can specify a constant voice for generation using the `history_prompt` parameter in the `generate_audio` function... The pattern is `{lang_code}_speaker_{0-9}`
> 
> Example: `audio_array = generate_audio(text_prompt, history_prompt="en_speaker_1")`
> 
> It has been mentionned in the documentation !

Where can I see all the speakers we can use and pass to history_prompt?

**Comment by gkucsko** [comment]
0-9 for all languages exist. you can load them in numpy and use the fine array with `codec_decode` to listen what they sound like

**Comment by droidworks** [comment]
Hi all, 

I noticed for East Indian languages, they have Hindi but not Tamil. Anyone know if there is a plan to include voices (male and female) for Bark?

Also, same question as above, it's tricky to get the same voice for every generation. Not sure if `history_prompt` really works.
