### ISSUE TITLE
How semantic tokens are generated for training?

### ISSUE THREAD

**Issue by gandolfxu** [suno-ai/bark#7]
Are you using a pretrained model? Where is the model?

**Comment by gkucsko** [comment]
Hey, to prevent unauthorized use of voice cloning we held back the semantic model for now. In our Studio we can add other safe guards but for the public version that’s difficult. If we come up with other ways of mitigate those risks going forward we would be open to releasing that as well, but for now it seems difficult

**Comment by yurtmete** [comment]
Do you think would it be meaningful to use w2v-bert to extract the semantic tokens for fine-tuning of first transformer (text model, semantic modeling)?  

I am suggesting w2v-bert as it was used AudioLM.
