### ISSUE TITLE
Manually download the model?

### ISSUE THREAD

**Issue by tupique** [suno-ai/bark#72]
Hey, first, thank you for this wonderful software! The demos are absolutely amazing!

However, I do have problem during preloading_models(), it will download the model (5.3 GB), but when it reached 2.05GB it throws an error "ERROR, something went wrong" without clear explanation what is going on behind the scene, and then it download the model from 0 again. Can this be simplified to download the model manually and/or resume the download instead of redownloading the whole model from start?

Thanks!

**Comment by gkucsko** [comment]
have a look at https://github.com/suno-ai/bark/issues/46 you can download them manually using wget with reconnect incase you have flaky internet and then move them into the right spot for bark to pick them up

**Comment by gkucsko** [comment]
feel free to reopen if not solved

**Comment by tupique** [comment]
Thanks a lot!
