### ISSUE TITLE
Slow Download Speeds when Running 'preload_models()' Command

### ISSUE THREAD

**Issue by AbhayGhante** [suno-ai/bark#74]
Mode of deployment: Google Colab GPU
The download speed of the "preload_models()" command is very slow, with speeds ranging from 200kb-400kb when executed.

**Comment by gkucsko** [comment]
strange, it's hosted on cloudflare. maybe try again in a bit? where are you located? (not sure if that matters for colab)

**Comment by doctoryfx** [comment]
can you share the download link of checkpoint files

**Comment by gkucsko** [comment]
see links here: https://github.com/suno-ai/bark/issues/46#issuecomment-1519055764

**Comment by gkucsko** [comment]
closing, feel free to reopen if issue continues
