### ISSUE TITLE
Solution for Missing Audio

### ISSUE THREAD

**Issue by BSalita** [suno-ai/bark#78]
Audio output was missing on local Windows 11 system having multiple audio devices. The solution was to use simpleaudio instead of IDisplay.Audio. winsound also worked.

    from bark import SAMPLE_RATE, generate_audio, preload_models

    # download and load all models
    preload_models()

    # generate audio from text
    text_prompt = """
         Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
         But I also have other interests such as playing tic tac toe.
    """
    audio_array = generate_audio(text_prompt)

    import simpleaudio as sa

    num_channels = 1
    bytes_per_sample = 4 # float32
    sample_rate = SAMPLE_RATE
    play_obj = sa.play_buffer(audio_array, num_channels, bytes_per_sample, SAMPLE_RATE)

    # Wait for playback to finish before exiting
    play_obj.wait_done()

**Comment by gkucsko** [comment]
unfortunately not very familiar with windows python, would love for someone to chime in who has a similar setup

**Comment by Trimad** [comment]
I tried your code snippet and a (screaming?) voice emanated from my Command Prompt, which I basically never, ever want to happen. Here's an alternative that uses pydub to save the tts as an mp3:

`from pydub import AudioSegment
import io

from bark import SAMPLE_RATE, generate_audio, preload_models

# download and load all models
preload_models()

# generate audio from text
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs] 
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)

# Save the audio_array as an MP3 file
audio_segment = AudioSegment(
    audio_array.tobytes(),
    frame_rate=SAMPLE_RATE,
    sample_width=audio_array.dtype.itemsize,
    channels=1
)

# Change 'your_output_filename.mp3' to your desired output file name
output_filename = 'your_output_filename.mp3'

# You can adjust the export parameters, such as bitrate, if needed.
audio_segment.export(output_filename, format="mp3", bitrate="192k")
`

**Comment by gkucsko** [comment]
haha sorry about that 😆  thanks for the snippet. closing for now unless issue continues
