### ISSUE TITLE
Limited to 13 seconds?

### ISSUE THREAD

**Issue by ShacharWeis** [suno-ai/bark#79]
All my attempts ended up cutting off after about 13 seconds. 

Even if I put longer text, it just stops. Any idea why?

**Comment by AhmedHathout** [comment]
Same here. Also for some reason, it skips sentences randomly every time I rerun

**Comment by wsippel** [comment]
Bark is not a regular screen reader, it's a generative AI. Most if not all generative AI models have a generation limit, and for Bark, that limit is about 13 to 15 seconds. You can use something like NLTK to tokenize the input, generate audio token by token, then concatenate the output. Adds some overhead and isn't perfectly stable, but it works. That how I implemented it in the Oobabooga extension.

**Comment by shengkaixuan** [comment]
> Bark is not a regular screen reader, it's a generative AI. Most if not all generative AI models have a generation limit, and for Bark, that limit is about 13 to 15 seconds. You can use something like NLTK to tokenize the input, generate audio token by token, then concatenate the output. Adds some overhead and isn't perfectly stable, but it works. That's how I implemented it in the Oobabooga extension.

any specific tutorials about what you did ???

**Comment by davidmartinrius** [comment]
> > Bark is not a regular screen reader, it's a generative AI. Most if not all generative AI models have a generation limit, and for Bark, that limit is about 13 to 15 seconds. You can use something like NLTK to tokenize the input, generate audio token by token, then concatenate the output. Adds some overhead and isn't perfectly stable, but it works. That's how I implemented it in the Oobabooga extension.
> 
> any specific tutorials about what you did ???

Actually, you just need NLTK to convert all phrases in an array. Then you can iterate the phrases and create an audio for each one. Once you got all the generated audios you can concatenate these.

**Comment by gkucsko** [comment]
great, would love some comments from people who have tried how to best stitch here: https://github.com/suno-ai/bark/pull/84
