### ISSUE TITLE
the audio is successfully generated, but the sound sounds a little strange.

### ISSUE THREAD

**Issue by cureai** [suno-ai/bark#8]
I am setting up a bark environment in wsl (ubuntu22) of window11, and the audio is successfully generated from the text, but the sound sounds a little strange.
Is there a setting I'm missing?
![image](https://user-images.githubusercontent.com/9191067/232801929-59703a0d-a93b-4cc5-b27e-016746f9dad6.jpg)
[audio.zip](https://github.com/suno-ai/bark/files/11262609/audio.zip)

**Comment by gkucsko** [comment]
I believe pydub likes int arrays. try:
```
int_audio_arr = (audio_arr * np.iinfo(np.int16).max).astype(np.int16)

AudioSegment(
    int_audio_arr.tobytes(),
    frame_rate=SAMPLE_RATE,
    sample_width=int_audio_arr.dtype.itemsize,
    channels=1,
)
```
