### ISSUE TITLE
Can a new language be added?

### ISSUE THREAD

**Issue by AigizK** [suno-ai/bark#9]
Can I add my language? My lang is endangered languages

**Comment by gkucsko** [comment]
That great, we are looking into adding more languages in the future, especially as generation quality goes up with less data. in the meantime if you have some data, you could look into using our models as a starting point to train your own. unfortunately our training code is too tied into other projects to release but there are some other great projects out there where you could get a sense on how to construct a training loop for finetuning, like: https://github.com/lucidrains/audiolm-pytorch

**Comment by sankam-nikolya** [comment]
@mcamac is it possible to expect support for the Ukrainian language?

**Comment by AigizK** [comment]
@mcamac Bashkir language. I have a male voice with 25+ hours of data and a female voice with 5+ hours

**Comment by blackyoko** [comment]
Brazillian Portuguese would be so nice as well!

**Comment by ekibagascan** [comment]
Please add Bahasa too

**Comment by gkucsko** [comment]
thanks putting on roadmap! will try to find a unified place for people to vote on upcoming language support!

**Comment by captainerd** [comment]
> thanks putting on roadmap! will try to find a unified place for people to vote on upcoming language support!

I would like spend some time to curate hours of speech and text to build datasets and learn about training a language, Regarding bark there are no much information around or scripts, from my understanding, you want to have the training 'closed source' ?
