### ISSUE TITLE
Can it highlight reading text?

### ISSUE THREAD

**Issue by bartekupartek** [suno-ai/bark#92]
Like in karaoke, would it be somehow doable to highlight which token is spoken?

**Comment by gkucsko** [comment]
hah fun. should be doable after the generation with some other tools. maybe in the future we could include timestamps in the output to make that easier.

**Comment by bartekupartek** [comment]
that would be super cool, I thought about words counter but timestamp could be also easily consumed by external tools

**Comment by bartekupartek** [comment]
@gkucsko any chance to bring it up? I wonder how to accurately adjust seconds to resulted samples, apologises for probably naive question but could it be calculated of generated audio samples divided by sampling rate, or do you have on top of your mind some good ideas where I might start?
