### ISSUE TITLE
How to run in windows 10!!?

### ISSUE THREAD

**Issue by merecesarchviz** [suno-ai/bark#93]
Hi,

I follow the basic instructions but once i try to lunch give errors!

![eorrrrrr](https://user-images.githubusercontent.com/79140456/233953944-e0ff4ea8-70ef-44d3-9ba8-4bf34dfddbe2.jpg)

How i can run it?

**Comment by 1qh** [comment]
you really should learn how shell and Python works ...

**Comment by hemangjoshi37a** [comment]
@merecesarchviz please try to always copy paste the code here so that it can be easily copy pasted inside Google or any other debugging instrument.

**Comment by merecesarchviz** [comment]
or those like me who need help to get all working, here is a tutorial showing how to set all, from a person who really likes to help and explain! https://www.youtube.com/watch?v=w41-MUfxIWo
