### ISSUE TITLE
Integrate Aim to track prompts and generated audios

### ISSUE THREAD

**Issue by roubkar** [suno-ai/bark#95]
Hey, Ruben from [Aim](https://github.com/aimhubio/aim) here! 👋

This is an awesome project!

Aim is a completely open-source and supercharged AI metadata tracker.
Aim can be helpful for the exploration and comparison of prompts and generated audio outputs.

<img width="1680" alt="Screen Shot 2023-04-24 at 13 48 57" src="https://user-images.githubusercontent.com/9951653/233962493-45faa824-9fb8-4b07-906e-d2a708f72ac8.png">

Aim repo: [http://github.com/aimhubio/aim](https://github.com/aimhubio/aim)
Aim docs: http://aimstack.readthedocs.io/

**Comment by gkucsko** [comment]
thanks, interesting, looks cool! might be a bit outside the scope of this repo and more suited for a fork, but happy to reconsider if lots of support for it.
