### ISSUE TITLE
No certificate issue

### ISSUE THREAD

**Issue by Deepwater1000** [suno-ai/bark#98]
Hello,

I have met below issue when I run the Python code, it seems there is no certificate, how to fix this?

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

**Comment by gkucsko** [comment]
hm not sure, but seems unrelated? when are you getting the error?

**Comment by 8bitben** [comment]
I got the same error using an older version of Python (3.10.2)

Updating Python to the latest version (3.11.3) seems to have newer SSL certificates and fixed the issue for me.

**Comment by Deepwater1000** [comment]
> hm not sure, but seems unrelated? when are you getting the error?
it happens after download all the necessary packages, here it looks like
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

**Comment by Deepwater1000** [comment]
> 

actually, I already use below version 
Python 3.11.3

**Comment by gkucsko** [comment]
some people had success with this: https://gist.github.com/marschhuynh/31c9375fc34a3e20c2d3b9eb8131d8f3

**Comment by Deepwater1000** [comment]
Many thanks this works and solve my issue.

**Comment by gkucsko** [comment]
Great!

**Comment by ableinc** [comment]
You don't need to update your Python version from 3.10 to 3.11. Please follow the instructions from this Stackoverflow answer (solved the issue for me): https://stackoverflow.com/a/70495761

**Comment by CREW8** [comment]
I could solve this Error in an Windows venv with the following steps:

1. I copied the Path for the File that should be downloaded and downloaded it manually.
2. I moved to file to the given location in the Error Message.
