### ISSUE TITLE
Apple Silicon increase speed

### ISSUE THREAD

**Issue by hankerbiao** [suno-ai/bark#99]
I need three minutes to generate a phrase now. Is there a good optimization method

**Comment by gkucsko** [comment]
a PR is in progress, waiting for some benchmark results from people: https://github.com/suno-ai/bark/pull/22

**Comment by 1c7** [comment]
<img width="296" alt="image" src="https://github.com/suno-ai/bark/assets/1804755/b420b768-cf87-476e-bf64-71134544d05a">

## Almost 4 minutes
<img width="1239" alt="image" src="https://github.com/suno-ai/bark/assets/1804755/2d6f4000-b02e-477b-8c17-2e37948a16ca">

**Comment by busraoguzoglu** [comment]
Having the same issue. If there is any update please let us know
